### ISSUE TITLE
Problem using REDIRECT/MASQUERADE/TPROXY with MPTCP

### ISSUE THREAD

**Issue by v-zza** [multipath-tcp/mptcp_net-next#328] opened 2022-12-16 01:26 UTC
I've run into an issue settup up iptables nat REDIRECT with mptcp. TL;DR: mptcpd/manager/monitor seem to see the network traffic before DNAT/SNAT is applied by iptable when using REDIRECT/MASQUERADE (or TPROXY).

### Setup:
- ss-server (shadowsocks) at 164.x.x.x:4201
- nc-server (netcat) at 164.x.x.x:8488
- ss-redir (for REDIRECT and TPROXY) running on client machine 127.0.0.1:12345
- nc-client running on client machine opening port 172.17.0.2:xyz
- ss-server/ss-redir/nc-server all use mptcpize, for nc-client, we try with and without mptcpize
- everything is running kernel 5.19.0-26, ip forwarding is enabled, mptcpd is running
- my test setup is running in docker, but iiuc the issue is unrelated to docker.

To keep this test minimal, I've only setup REDIRECT for TCP (TPROXY is needed for udp). This is the ip table setup that I set via "iptables-restore rules", with "rules" file containing this (excluding logging): 

```
*nat
-N SHADOWSOCKS

# ignore packets to ss-server:8488 and local
-A SHADOWSOCKS -d 164.x.x.x/32 -p tcp --dport 8488 -j RETURN
-A SHADOWSOCKS -d 172.17.0.0/12 -j RETURN

-A SHADOWSOCKS -p tcp -j REDIRECT --to-ports 12345
-A PREROUTING ! -i lo -p tcp -j SHADOWSOCKS
-A OUTPUT -p tcp -j SHADOWSOCKS
-A POSTROUTING -j MASQUERADE
COMMIT
```

### Running nc-client without mptcpize:
- As expected nc-client transparently stablishes a TCP connection to the ss-redir (instead of ss-server using DNAT/SNAT).
- MPTCP is not used for communication between nc-client (172.17.0.2:44762) and ss-redir (127.0.0.1:12345) since nc-client uses a normal TCP socket.
- Follow on connections to ss-server and nc-server are established correctly and everything works as expected.
- Logs from the network and output from "ip mptcp monitor" (with some cleanup) are blow:

```
SYN from 172.17.0.2:44762 to 164.x.x.x:4021
[mangle-output]   IN= OUT=eth0         SRC=172.17.0.2 DST=164.x.x.x LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=49960 DF PROTO=TCP SPT=44762 DPT=4201  WINDOW=64240 RES=0x00 SYN URGP=0 OPT (020405B40402080A2EBC18250000000001030307) 
DNAT 164.x.x.x:4021 -> 127.0.0.1:12345
[nat-postrouting] IN= OUT=lo           SRC=172.17.0.2 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=49960 DF PROTO=TCP SPT=44762 DPT=12345 WINDOW=64240 RES=0x00 SYN URGP=0 OPT (020405B40402080A2EBC18250000000001030307) 
[mangle-input]    IN=lo OUT= MAC=00... SRC=172.17.0.2 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=49960 DF PROTO=TCP SPT=44762 DPT=12345 WINDOW=64240 RES=0x00 SYN URGP=0 OPT (020405B40402080A2EBC18250000000001030307) 

SYN/ACK from 127.0.0.1:12345 to 172.17.0.2:44762
[mangle-output]   IN= OUT=lo           SRC=127.0.0.1 DST=172.17.0.2 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=12345 DPT=44762 WINDOW=65483 RES=0x00 ACK SYN URGP=0 OPT (0204FFD70402080AEA4B906A2EBC182501030307) 
SNAT 127.0.0.1:12345 -> 164.x.x.x:4021
[mangle-input]    IN=lo OUT= MAC=00... SRC=164.x.x.x DST=172.17.0.2 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=4201  DPT=44762 WINDOW=65483 RES=0x00 ACK SYN URGP=0 OPT (0204FFD70402080AEA4B906A2EBC182501030307) 

SYN from 172.17.0.2:44762 to 164.x.x.x:4021
[mangle-output]         IN= OUT=eth0         SRC=172.17.0.2 DST=164.x.x.x LEN=52 TOS=0x00 PREC=0x00 TTL=64 ID=49961 DF PROTO=TCP SPT=44762 DPT=4201  WINDOW=502 RES=0x00 ACK URGP=0 OPT (0101080A2EBC1825EA4B906A) 
DNAT 164.x.x.x:4021 -> 127.0.0.1:12345
[mangle-input]          IN=lo OUT= MAC=00... SRC=172.17.0.2 DST=127.0.0.1 LEN=52 TOS=0x00 PREC=0x00 TTL=64 ID=49961 DF PROTO=TCP SPT=44762 DPT=12345 WINDOW=502 RES=0x00 ACK URGP=0 OPT (0101080A2EBC1825EA4B906A) 

Follow on connections...
```

### Running nc-client with mptcpize:
- All traffic has mptcp enabled (see TCP options in the logs below).
- The SYN request from nc-client (172.17.0.2:39098) to nc-server (164.x.x.x:4021) is redirected with DNAT to ss-redir (127.0.0.1:12345) as before.
- The SYN/ACK response is sent back from ss-redir (127.0.0.1:12345) to nc-client (172.17.0.2:39098). SNAT changes the source to nc-server (164.x.x.x:4021) as before.
- MPTCP daemon/manager/monitor seem to see the traffic before DNAT SNAT happens and falsely assumes that this SYN/ACK is a new connection request from 127.0.0.1. it **prints a second (incorrect) [CREATED] message and assigns a new token to the flow (73774a55)**.
- ACK is sent from nc-client to nc-server, and is redirected to ss-redir. **MPTCP monitor shows a connection is established in the reverse order** (since it assumed 127.0.0.1:12345 had initiated the connection in the step above).
- Needless to say nothing works after this step. No follow on connections are made to ss-server.
- Logs below show the steps. Note that MPTCP_ENABLED TCP options are correctly passed around with keys exchanged and in the correct order.

```
SYN from 172.17.0.2:39098 to 164.x.x.x:4021
[MPTCP-MONITOR-CREATED] token=3b8b1d22 remid=0 locid=0 saddr4=172.17.0.2 daddr4=164.x.x.x sport=39098 dport=4201
[mangle-output]   IN= OUT=eth0         SRC=172.17.0.2 DST=164.x.x.x LEN=64 TOS=0x00 PREC=0x00 TTL=64 ID=42037 DF PROTO=TCP SPT=39098 DPT=4201  WINDOW=64240 RES=0x00 SYN URGP=0 OPT (020405B40402080A2ED767720000000001030307 / 1E040101) 
DNAT 164.x.x.x:4021 -> 127.0.0.1:12345
[nat-postrouting] IN= OUT=lo           SRC=172.17.0.2 DST=127.0.0.1 LEN=64 TOS=0x00 PREC=0x00 TTL=64 ID=42037 DF PROTO=TCP SPT=39098 DPT=12345 WINDOW=64240 RES=0x00 SYN URGP=0 OPT (020405B40402080A2ED767720000000001030307 / 1E040101) 
[mangle-input]    IN=lo OUT= MAC=00... SRC=172.17.0.2 DST=127.0.0.1 LEN=64 TOS=0x00 PREC=0x00 TTL=64 ID=42037 DF PROTO=TCP SPT=39098 DPT=12345 WINDOW=64240 RES=0x00 SYN URGP=0 OPT (020405B40402080A2ED767720000000001030307 / 1E040101) 

SYN/ACK from 127.0.0.1:12345 to 172.17.0.2:39098
[MPTCP-MONITOR-CREATED] token=73774a55 remid=0 locid=0 saddr4=127.0.0.1 daddr4=172.17.0.2 sport=12345 dport=39098
[mangle-output]   IN= OUT=lo           SRC=127.0.0.1 DST=172.17.0.2 LEN=72 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=12345 DPT=39098 WINDOW=65483 RES=0x00 ACK SYN URGP=0 OPT (0204FFD70402080AEA66DFB72ED7677201030307 / 1E0C0101 6A5C01948F2ACE8A) 
SNAT 127.0.0.1:12345 -> 164.x.x.x:4021
[mangle-input]    IN=lo OUT= MAC=00... SRC=164.x.x.x DST=172.17.0.2 LEN=72 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=4201  DPT=39098 WINDOW=65483 RES=0x00 ACK SYN URGP=0 OPT (0204FFD70402080AEA66DFB72ED7677201030307 / 1E0C0101 6A5C01948F2ACE8A) 

SYN from 172.17.0.2:44762 to 164.x.x.x:4021
[mangle-output]   IN= OUT=eth0         SRC=172.17.0.2 DST=164.x.x.x LEN=72 TOS=0x00 PREC=0x00 TTL=64 ID=42038 DF PROTO=TCP SPT=39098 DPT=4201  WINDOW=502 RES=0x00 ACK URGP=0 OPT (0101080A2ED76773EA66DFB7 / 1E140101 568DEA78540B18F7 6A5C01948F2ACE8A) 
DNAT 164.x.x.x:4021 -> 127.0.0.1:12345
[mangle-input]    IN=lo OUT= MAC=00... SRC=172.17.0.2 DST=127.0.0.1 LEN=72 TOS=0x00 PREC=0x00 TTL=64 ID=42038 DF PROTO=TCP SPT=39098 DPT=12345 WINDOW=502 RES=0x00 ACK URGP=0 OPT (0101080A2ED76773EA66DFB7 / 1E140101 568DEA78540B18F7 6A5C01948F2ACE8A) 
[MPTCP-MONITOR-ESTABLISHED] token=73774a55 remid=0 locid=0 saddr4=127.0.0.1 daddr4=172.17.0.2 sport=12345 dport=39098

No follow on connection to ss-server, since the initial connection is messed up.
```

I'm not sure what's the best solution to resolve this, as it seems like kernel nat and mptcp support are having a weird interactions. My thoughts:
- Just looking at the packet and seeing its a SYN/ACK, or checking the tcp options that has an mptcp key attached should already tell the mptcp manager/monitor that this is not a new request. I'm surprised the monitor is showing a wrong [CREATED] message for SYN/ACK.
- The nat mapping in the kernel can be accessed via "conntrack -L":
tcp      6 427631 ESTABLISHED src=172.17.0.2 dst=164.x.x.x sport=39098 dport=4201 src=127.0.0.1 dst=172.17.0.2 sport=12345 dport=39098 [ASSURED] mark=0 use=1
so at least in principle mptcp could take this information and use it to determine that SYN/ACK from 127.0.0.1:12345 is not a new request.
- I'm not sure where exactly the mptcp manager/monitor intercept the network packet, but it seems to happen before DNAT/SNAT is applied. Maybe there is a way to move the interception point?
- There might be a different REDIRECT/TPROXY setup that solves the issue, but I'm not familiar enough with the tool chain to figure that out.

**Comment by matttbe** [comment] 2022-12-21 17:43
Hi @v-zza 

Thank you for the detailed bug report!

But I'm sorry, I'm a bit lost: where are the different log messages coming from?

MPTCP should have the view before the modifications from Netfilter in OUTPUT and after it in INPUT. But maybe some hooks for the establishment bit are done before the modifications from Netfilter.
Just to be sure I understand the issue properly: with only one MPTCP connection here, you get two CREATED events with two different token (and different 5-tuples) suggesting the SYN and SYN+ACK are not linked to each others from an MPTCP point of view, causing the rest of the connection to stop?

> so at least in principle mptcp could take this information and use it to determine that SYN/ACK from 127.0.0.1:12345 is not a new request.

we cannot depend on Conntrack but I understand the idea that if connections are modified with Netfilter later, we might have to ask Netfilter for more info.

> I'm not sure where exactly the mptcp manager/monitor intercept the network packet, but it seems to happen before DNAT/SNAT is applied. Maybe there is a way to move the interception point?

From what I remembered, it might be very hard to move this but maybe we can get more info elsewhere or update info later.

> There might be a different REDIRECT/TPROXY setup that solves the issue, but I'm not familiar enough with the tool chain to figure that out.

That would be nice if you could do the validation with TPROXY instead of REDIRECT.
The doc for it is there: https://www.kernel.org/doc/html/latest/networking/tproxy.html

It looks like the Shadowsocks implementation in Rust has a script to use TPROXY instead of a REDIRECT with TCP: https://github.com/shadowsocks/shadowsocks-rust/blob/master/configs/iptables_tproxy.sh
But TPROXY should work: https://github.com/multipath-tcp/mptcp_net-next/commit/5fb62e9cd3adadd95303447ee8e3f62ee98b0e73

**Comment by v-zza** [comment] 2022-12-22 23:40
Thanks for the pointers. I finally manged to setup a TPROXY with ss-redir (based on [this](https://github.com/shadowsocks/shadowsocks-libev#transparent-proxy-pure-tproxy)) that manages to establish an MPTCP connections and pass the data to the server. But it comes with a big caveat that makes it difficult/impossible to have an MPTCP join operation. In my use case, I have an nc-client that can use two different relays/path to a remote ss-server through two instances of ss-redir (ssgw0 and ssgw1).

ss-redir is acting on behalf of the remote nc-server as TPROXY, opening a local socket (later converted by mptcize) with a non-local address (ip of the nc-server). Crucially, the local socket (that ss-redir listens on) is using its own MPTCP keys/tokens to talk to to the nc-client (rather than relaying the key/token from the remote nc-server, as a real transparent proxy would be able to do). We end up with connections like this, where `==` is an MPTCP-enabled connection:

```
nc-client ==== ss-redir (ssgw0) ==== ss-server ==== nc-server
      \======= ss-redir (ssgw1) ==== ss-server ==== nc-server
```

Any join operation applied to the any of these connection only affects that leg of the connection. In particular, **if nc-client tries to add a new subflow that goes through ss-redir-1, ss-redir-1 would respond with "mptcp unknwon"**. nc-client thinks it's talking to the nc-server, but the SYN with join request is intercepted and answered by the local socket impersonating the remote server.

I took the TPROXY setup from [here](https://github.com/shadowsocks/shadowsocks-libev#transparent-proxy-pure-tproxy) with some modifications. The docker setup is a bit verbose to include here (I can provide if needed), but [here](https://docs.google.com/document/d/e/2PACX-1vSZ9UpAs26CLg0ydhzGP13l_3WA9x21obd0CQ9Px227FPHLJCBPfVLpC6RUFSC75-IKvFUUsGtuNGwy/pub) is the trace with tcpdump and mptcp monitor logs (cleaned up with annotations). TL;DR is that ss-redir, instead of relaying nc-server's MPTCP keys, uses it's own keys to initiate the connection with the nc-client. Here is what I could construct from the logs (relative timings might not be exact):

![ss-redir-tproxy-dataflow](https://user-images.githubusercontent.com/117123308/209232831-2d355aa5-0be8-41f2-91ed-97a1ed41b07a.png)


I'm a bit lost as what might be good solution here, assuming **ss-redir/ss-server connection (possibly via relays) is the only viable TCP connection in my target network environment**. Some thoughts:
- This problem is rooted in having a local socket (ss-redir) that does not forward MPTCP keys, but rather impersonates a remote socket using its own key/tokens. One could add support for ss-redir to wait until it gets the MPTCP key from the nc-server and uses it to respond to nc-client. But I'm not sure if how a true MPTCP transparent proxy can be implemented to support follow up join requests (token passing, hmac stuff, etc). 

- I can add a pair of helper/relay software (somewhat similar to HCPE/HAG) to deal with the connection requirements. But here (as opposed to HCPE/HAG) the inner connections are *not* end-to-end MPTCP-enabled, even-though each leg of the connection may or may not be MPTCP-enabled. So the helper software is quite different from HCPE/HAG setup. It would need to interface with nc-client/nc-server with MPTCP sockets, and relay the traffic (including keys/token/etc) via several base TCP connections. In such setup, if nc-client sends a join request on eth2, the helper software (fake-nc-server) sends that packet via ssgw2 to the the other helper software (fake-nc-client), and the response with nc-server's true MPTCP key is relayed back to the nc-client.

```
nc-client [eth0/1/2] == fake-nc-server -- ss-redir (ssgw0) --- ss-server -- fake-nc-client == [eth0] nc-server
                                   | \--- ss-redir (ssgw1) --- ss-server ---/ |
                                    \---- ss-redir (ssgw2) --- ss-server ----/
                                                
                                                            ^       
                                                           /|\
                                                            |
                                                        
                                                 unreliable connections 

```

How easy/difficult do you think it might be to implement such helper software, and what language might have better support for such implementation?

**Comment by matttbe** [comment] 2022-12-23 10:41
Sorry, I'm still a bit lost between what you want to achieve, what you did and what you got.

Here is a summary, please correct me:
- with REDIRECT + MASQUERADE, the MPTCP connection is established: SYN & SYN+ACK & 3rd ACK exchanged but nothing after, right? (maybe not seen as established from both the client and server if you check with `ss -Menita`)
- with TPROXY, it seems to work but what you want instead is one subflow to communicate with `ss-redir` and another one to discuss directly with the end-server?

I'm a bit confused by what you said about forwarding MPTCP keys: each time you use a proxy, you terminate the connection at the proxy and create a new one with the next one. In other words, you have:
- one connection between the client and the proxy client
- one between the proxy client and the proxy server
- one between the proxy server and the end server

These are different MPTCP/TCP connections, you can only established subflows within the established connection: you can have multiple paths but the hosts have to be the same. So here, the client and end server doesn't talk to each others directly.

If you want the client and end server to talk directly using multiple paths, you might need to use tunnels (VPN, etc.) or make sure the traffic can be routed where you want (inside or outside tunnels).

Typically, an MPTCP connection is created only between the proxy client and proxy server because the client doesn't have the capability or the view on the different networks. But from what I understood, that's not what you want. If yes, it is unclear to me what you want to achieve :)

**Comment by v-zza** [comment] 2022-12-25 20:37
You summary is correct. I do want to have an end-to-end MPTCP connection between nc-client and nc-server and VPN over shadowsocks would allow for that (e.g. OMR supports this functionality). But VPN is very heavy handed for my use case and ends up very unstable and slow.

Re "Typically, an MPTCP connection is created only between the proxy client and proxy serve": I'm using nc-client/nc-server for experimentation here. I'll change this to ss-redir/ss-server once I manage to establish an end-to-end MPTCP connection.

My real setup has relay nodes sitting between ss-redir and ss-server which adds yet another leg to the connection. E.g. I might have two path to the server via two different relays:
nc-client --- ss-redir --- relay0 --- ss-server --- nc-server 
nc-client --- ss-redir --- relay1 --- ss-server --- nc-server 
Unlike your average MPTCP setup, these connections each have a few Mbps of up/down bandwidth and are very unstable.

One potential solution that involves code change to ss-server/ss-redir: when ss-redir get SYN from nc-client, it does not immediately send back ACK/SYN. Instead it relays the SYN all the way to the nc-server (via ss-server), and when it has the SYN/ACK form the nc-server, it relays it back to the client (which would now have nc-server's mptcp key in the tcp options). This would add half a round trip to the overall connection setup (data packet needs to wait for the SYN/ACK from the nc-server to arrive at the client side), but would make it possible for nc-client and nc-server to establish an end-to-end MPTCP connection that I can join into via another path.

Another solution is something like what I described in the previous post: helper software that sit before ss-redir and after ss-server, and act on behalf of the nc-server and nc-client (truly) transparently. This solution might be more generic as I can use other forms of obfuscated transport as inner connection.

**Comment by matttbe** [comment] 2022-12-26 10:06
Hosts cannot exchange MPTCP keys: you would need to share more than that (seq num, etc.) to allow what you want and the protocol is not designed for that.

The TCP proxy you use (ss-redir, etc.) acts on the OSI layer 4 (Transport layer), the same as for MPTCP. It means that "transparent" TCP proxy can transfer data but they create new layer 4 connections: you have different TCP connections "on each side", carrying the same data, with or without an extra layer of encryption. Because you have different TCP connections, they are between 2 fixed hosts (client/server) and you cannot mix them.

If you want to have an end-to-end MPTCP connection, you need to rely on layer 3 (and < 3) protocols to go through the different paths you want. There are multiple techniques for that: simple routing, encapsulation (tunnel, e.g. Wireguard or GRE tunnels, one tunnel per path), IPv6 source routing, MPLS, etc.
But then, the issue is not really linked to MPTCP any more, right? :)

**Comment by v-zza** [comment] 2022-12-26 22:02
The reason I want to use MPTCP here is to avoid having to implement load balancing, re-transmission and fallback logic. I have also considered using vanilla routing (running openWrt on the client side as done in OMR) to maybe just have simple load balancing and hope that different connections end up using different paths to the server. But that would still limit each connection's bandwidth.

I'll check to see if there is a light-weight encapsulation option that can hold a steady connection in my setup. Proper vanilla VPN is very heavy handed and typical VPN connections would not hold with my setup. At the very least I need to have fast-open enabled to allow for faster reconnects. By I still see this as the "lazy" solution. I think at least in principle a proper layer 4 mptcp-proxy chain solution is viable (in spirit along the lines of RTT0). We would need a mechanism to join into an MPTCP connection via an explicit proxy rather than an endpoint defined on a local interface. I assume such setup is not (yet) common enough to warrant a protocol definition, so I'm on my own going either way.

**Comment by matttbe** [comment] 2022-12-27 14:11
Why is it not possible for you to route different subflows through different paths?
If your client and/or server can have multiple IPs, can you not add some routing rules to achieve what you want without using tunnels? You can tell a host that depending on the source/destination/(many other things), it can route the traffic through one path or another.
(but yes, that's not specific to MPTCP, you will find more hints and help elsewhere)

**Comment by matttbe** [comment] 2023-01-02 17:11
Hello,

Because at the end, this issue cannot be addressed by MPTCP, I suggest to close it.

**Closed as completed by matttbe** 2023-01-02 17:11 UTC
Labels: question
