### ISSUE TITLE
WARNING: Bad mapping: ssn=1 map_seq=498340137 map_data_len=79

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#34] opened 2020-06-01 19:07 UTC
Hit it once, while running apache-benchmark stress-test with 100 concurrent clients up to 100k requests for file-sizes of 1KB (aka., test "simple_ab").

```
server login: [   57.507531] ------------[ cut here ]------------
[   57.514702] Bad mapping: ssn=1 map_seq=498340137 map_data_len=79
[   57.514965] WARNING: CPU: 2 PID: 21 at net/mptcp/subflow.c:602 warn_bad_map.isra.0.part.0+0x3e/0x50
[   57.517687] Kernel panic - not syncing: panic_on_warn set ...
[   57.518693] CPU: 2 PID: 21 Comm: ksoftirqd/2 Kdump: loaded Not tainted 5.7.0-rc6.mptcp #72
[   57.520067] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.12.1-0-ga5cab58e9a3f-prebuilt.qemu.org 04/01/2014
[   57.522082] Call Trace:
[   57.522587]  dump_stack+0x76/0xa0
[   57.523332]  panic+0x19a/0x389
[   57.527019]  __warn.cold+0x25/0x2d
[   57.528493]  report_bug+0x10f/0x140
[   57.529145]  do_error_trap+0xcf/0x100
[   57.530655]  do_invalid_op+0x3e/0x50
[   57.532445]  invalid_op+0x1e/0x30
[   57.533104] RIP: 0010:warn_bad_map.isra.0.part.0+0x3e/0x50
[   57.534067] Code: 55 4b d9 00 01 e8 22 51 6a ff 44 8b 6d 00 48 89 df e8 16 51 6a ff 8b 13 44 89 e6 48 c7 c7 c0 4d 33 82 44 89 e9 e8 29 56 4a ff <0f> 0b 5b 5d 41 5c 41 5d c3 66 0f 1f 84 00 00 00 00 00 55 ba 80 00
[   57.537416] RSP: 0018:ffff88811ad9ef18 EFLAGS: 00010282
[   57.538372] RAX: 0000000000000000 RBX: ffff88811743c63c RCX: 0000000000000000
[   57.539857] RDX: 0000000000000004 RSI: ffffffff82f28fd4 RDI: ffffed10235b3dd5
[   57.541131] RBP: ffff88811743c644 R08: 0000000000000001 R09: fffffbfff05e5297
[   57.542377] R10: ffffffff82f294b3 R11: fffffbfff05e5296 R12: 0000000000000001
[   57.543692] R13: 000000000000004f R14: ffff8881188e02f7 R15: ffff88811743c600
[   57.545974]  mptcp_subflow_data_available+0xce8/0xec0
[   57.548493]  subflow_data_ready+0xcb/0x160
[   57.550768]  tcp_data_queue+0x7ae/0x1a30
[   57.555834]  tcp_rcv_established+0x38f/0xa90
[   57.560276]  tcp_v4_do_rcv+0x253/0x350
[   57.560937]  tcp_v4_rcv+0x145b/0x1580
[   57.563106]  ip_protocol_deliver_rcu+0x37/0x270
[   57.563890]  ip_local_deliver_finish+0xa9/0xc0
[   57.564653]  ip_local_deliver+0x1b4/0x1c0
[   57.566978]  ip_sublist_rcv_finish+0x84/0xa0
[   57.567712]  ip_sublist_rcv+0x22c/0x310
[   57.572038]  ip_list_rcv+0x1e4/0x225
[   57.574483]  __netif_receive_skb_list_core+0x439/0x460
[   57.577686]  netif_receive_skb_list_internal+0x3e3/0x560
[   57.580386]  gro_normal_list.part.0+0x14/0x50
[   57.581154]  napi_gro_receive+0x6a/0xb0
[   57.581837]  receive_buf+0x371/0x1cf0
[   57.585596]  virtnet_poll+0x2b7/0x5a0
[   57.587867]  net_rx_action+0x1ec/0x4c0
[   57.590169]  __do_softirq+0xfc/0x29c
[   57.592258]  run_ksoftirqd+0x15/0x20
[   57.592886]  smpboot_thread_fn+0x19d/0x2d0
[   57.595639]  kthread+0x1cc/0x1f0
[   57.597146]  ret_from_fork+0x35/0x40
```

**Comment by cpaasch** [comment] 2020-06-05 14:26
Syzkaller also hit it

```
------------[ cut here ]------------
Bad mapping: ssn=65435 map_seq=32718 map_data_len=32717
WARNING: CPU: 1 PID: 16 at net/mptcp/subflow.c:546 warn_bad_map.isra.0.part.0+0x2c/0x40 net/mptcp/subflow.c:546
Kernel panic - not syncing: panic_on_warn set ...
CPU: 1 PID: 16 Comm: ksoftirqd/1 Not tainted 5.8.0-rc1 #4
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
Call Trace:
 __dump_stack lib/dump_stack.c:77 [inline]
 dump_stack+0x99/0xce lib/dump_stack.c:118
 panic+0x18b/0x4e5 kernel/panic.c:231
 __warn.cold+0x2a/0x34 kernel/panic.c:600
 report_bug+0x182/0x1d0 lib/bug.c:198
 exc_invalid_op+0xa7/0xf0 arch/x86/kernel/traps.c:235
 asm_exc_invalid_op+0x12/0x20 arch/x86/include/asm/idtentry.h:563
RIP: 0010:warn_bad_map.isra.0.part.0+0x2c/0x40 net/mptcp/subflow.c:546
Code: 49 89 f4 55 89 d5 53 48 89 fb e8 4f 5f 44 ff 41 8b 0c 24 8b 13 89 ee 48 c7 c7 40 68 52 82 c6 05 7d e1 9a 00 01 e8 c7 52 35 ff <0f> 0b 5b 5d 41 5c c3 0f 1f 00 66 2e 0f 1f 84 00 00 00 00 00 55 48
RSP: 0018:ffffc9000008ba40 EFLAGS: 00010286
RAX: 0000000000000000 RBX: ffff8880a0b95f3c RCX: ffffffff810e23d6
RDX: 0000000000000000 RSI: ffffffff810e3893 RDI: 0000000000000006
RBP: 000000000000ff9b R08: ffff88813b115e80 R09: 0000000000000037
R10: 0000000000003400 R11: 0000000000add800 R12: ffff8880a0b95f44
R13: ffff8880a062b600 R14: ffff8880a0b95f00 R15: 0000000000007fcd
 warn_bad_map net/mptcp/subflow.c:578 [inline]
 validate_mapping net/mptcp/subflow.c:578 [inline]
 get_mapping_status net/mptcp/subflow.c:696 [inline]
 subflow_check_data_avail net/mptcp/subflow.c:734 [inline]
 mptcp_subflow_data_available+0x8da/0xa20 net/mptcp/subflow.c:840
 subflow_state_change+0x8b/0x230 net/mptcp/subflow.c:1133
 tcp_fin+0x105/0x250 net/ipv4/tcp_input.c:4191
 tcp_data_queue+0xcbb/0x1540 net/ipv4/tcp_input.c:4822
 tcp_rcv_established+0x2ef/0xa10 net/ipv4/tcp_input.c:5735
 tcp_v4_do_rcv+0x23e/0x360 net/ipv4/tcp_ipv4.c:1629
 tcp_v4_rcv+0x116e/0x12b0 net/ipv4/tcp_ipv4.c:2011
 ip_protocol_deliver_rcu+0x1f/0x150 net/ipv4/ip_input.c:204
 ip_local_deliver_finish net/ipv4/ip_input.c:231 [inline]
 NF_HOOK include/linux/netfilter.h:421 [inline]
 ip_local_deliver+0xc8/0xe0 net/ipv4/ip_input.c:252
 dst_input include/net/dst.h:441 [inline]
 ip_rcv_finish net/ipv4/ip_input.c:428 [inline]
 ip_rcv_finish net/ipv4/ip_input.c:414 [inline]
 NF_HOOK include/linux/netfilter.h:421 [inline]
 ip_rcv+0x70/0xa0 net/ipv4/ip_input.c:539
 __netif_receive_skb_one_core+0xd4/0x100 net/core/dev.c:5279
 __netif_receive_skb+0x27/0xa0 net/core/dev.c:5393
 process_backlog+0xc4/0x180 net/core/dev.c:6237
 napi_poll net/core/dev.c:6682 [inline]
 net_rx_action+0x190/0x500 net/core/dev.c:6750
 __do_softirq+0xdb/0x2d8 kernel/softirq.c:292
 run_ksoftirqd kernel/softirq.c:630 [inline]
 run_ksoftirqd+0x15/0x20 kernel/softirq.c:622
 smpboot_thread_fn+0x16a/0x250 kernel/smpboot.c:165
 kthread+0x126/0x170 kernel/kthread.c:291
 ret_from_fork+0x22/0x30 arch/x86/entry/entry_64.S:293
Dumping ftrace buffer:
   (ftrace buffer empty)
Kernel Offset: disabled
```

2d948a5e3ead ("mptcp: check for plain TCP sock at accept time")  (HEAD) (10 minutes ago) <Paolo Abeni>
404b0abd5a9a ("mptcp: support IPV6_V6ONLY setsockopt")  (2 hours ago) <Florian Westphal>
5355be031726 ("mptcp: add REUSEADDR/REUSEADDR support")  (2 hours ago) <Florian Westphal>
84f9bcd3c1fc ("net: use mptcp setsockopt function for SOL_SOCKET on mptcp sockets")  (2 hours ago) <Florian Westphal>
0ec5e66cad3d ("selftests/mptcp: Capture pcap on both sender and receiver")  (2 hours ago) <Christoph Paasch>
952f6a124c54 ("[DO-NOT-MERGE] mptcp: enabled by default")  (tag: export/20200616T013825, mptcp_net-next/export) (15 hours ago) <Matthieu Baerts>
b6b8b806d196 ("[DO-NOT-MERGE] mptcp: use kmalloc on kasan build")  (15 hours ago) <Paolo Abeni>
c8807b1a95bf ("mptcp: close poll() races")  (15 hours ago) <Paolo Abeni>
9c7e7ff6ae82 ("mptcp: add receive buffer auto-tuning")  (15 hours ago) <Florian Westphal>
c8c1a0fa124d ("selftests: mptcp: add option to specify size of file to transfer")  (15 hours ago) <Florian Westphal>
0e68992d6388 ("mptcp: fallback in case of simultaneous connect")  (15 hours ago) <Davide Caratti>
147ecccbdcfd ("net: mptcp: improve fallback to TCP")  (15 hours ago) <Davide Caratti>
25794826eef9 ("mptcp: introduce token KUNIT self-tests")  (15 hours ago) <Paolo Abeni>
5d5fbf5ff0ab ("mptcp: move crypto test to KUNIT")  (15 hours ago) <Paolo Abeni>
56530a96472e ("mptcp: do nonce initialization at subflow creation time")  (15 hours ago) <Paolo Abeni>
7a138a019419 ("mptcp: refactor token container")  (15 hours ago) <Paolo Abeni>
1dd535944bd5 ("mptcp: add __init annotation on setup functions")  (15 hours ago) <Paolo Abeni>
292de252c180 ("mptcp: drop MP_JOIN request sock on syn cookies")  (15 hours ago) <Paolo Abeni>
9bdf5797a7c0 ("mptcp: cache msk on MP_JOIN init_req")  (15 hours ago) <Paolo Abeni>
b3a9e3b9622a ("Linux 5.8-rc1")  (tag: v5.8-rc1, netnext/master, mptcp_net-next/net-next) (2 days ago) <Linus Torvalds>

[EDIT June 17th: Updated HEAD & calltrace]

**Comment by cpaasch** [comment] 2020-06-22 19:38
Got a hit with Paolo's debug-patch:

```
MPTCP: msk ffff8880b139ee80 flags 3 server side 1 skb len 0 fin 1 data_fin 1
MPTCP: msk ffff8880b139ee80 flags b server side 1 skb len 0 fin 1 data_fin 1
Bad mapping: ssn=65435 map_seq=32718 map_data_len=32717
```

**Comment by pabeni** [comment] 2020-06-24 10:52
reporting here IRC discussion for future memory: the issue is triggered by a 0 len skb carrying TCP FIN, MPTCP DATA FIN and DSS with data_len > 1. This latter is not correct WRT the RFC - data_len should be == 1 for 0len MPTCP DATA FIN packets.

The issue is likely on the sender side, tentative patch is:

```
diff --git a/net/mptcp/options.c b/net/mptcp/options.c
index f464f8669dfc..46470194b8ca 100644
--- a/net/mptcp/options.c
+++ b/net/mptcp/options.c
@@ -451,9 +451,9 @@ static bool mptcp_established_options_mp(struct sock *sk, struct sk_buff *skb,
 }

 static void mptcp_write_data_fin(struct mptcp_subflow_context *subflow,
-                                struct mptcp_ext *ext)
+                                struct sk_buff *skb, struct mptcp_ext *ext)
 {
-       if (!ext->use_map) {
+       if (!ext->use_map || !skb->len) {
                /* RFC6824 requires a DSS mapping with specific values
                 * if DATA_FIN is set but no data payload is mapped
                 */
@@ -505,7 +505,7 @@ static bool mptcp_established_options_dss(struct sock *sk, struct sk_buff *skb,
                        opts->ext_copy = *mpext;

                if (skb && tcp_fin && subflow->data_fin_tx_enable)
-                       mptcp_write_data_fin(subflow, &opts->ext_copy);
+                       mptcp_write_data_fin(subflow, skb, &opts->ext_copy);
                ret = true;
        }
```

**Comment by pabeni** [comment] 2020-07-08 15:38
should be resolved in current export after:

"mptcp: fix DSS map generation on fin retransmission"

**Closed as completed by pabeni** 2020-07-08 15:38 UTC
Labels: bug, syzkaller
