### ISSUE TITLE
mptcpize, rsyncd & connection tear down (hangs)?

### ISSUE THREAD

**Issue by daire-byrne** [multipath-tcp/mptcp_net-next#295] opened 2022-08-18 22:23 UTC
Hi,

We have been using mptcp to do a bunch of bulk rsync transfers between hosts of late, and have been using the rsync daemon at one end (rather than ssh). This starts an "rsync --daemon" process and spawns a new one for every incoming client connection (mptcpize run rsync -av hostB::/blah/ /blah/").

We have added the LD_PRELOAD environment into the rsyncd.service (override) file to enable mptcp connectivity.

This is all working fine and we have multiple interfaces partaking in the transfer. However, we noticed that if we kill (term/kill) the client rsync during a transfer, it does not cause the remote rsyncd process to close as expected. I assume something about the connection tear down when the client suddenly dies it not working?

If I do the same over normal TCP (rsync -av hostB::/blah/ /blah/") and kill that, then the remote rsyncd process dies and closes successfully. It just so happens we have some automated processes that can "preempt" rsync processes by killing them so after a few days we end up with hundred of "hung" rsync daemon processes on the remote server.

I'm not entirely sure how best to further debug this so any pointers would be gratefully accepted.

Our endpoint and limits setup is idnetical on both client and server and is pretty simple:

ip mptcp endpoint show
10.15.21.251 id 1 signal dev ens224 
10.15.22.251 id 2 signal dev ens256 
10.15.20.251 id 3 signal dev ens192 

ip mptcp limits show
add_addr_accepted 4 subflows 4

We are running the 5.17 kernel atm but I plan to test on the v5.19 kernel too.

Cheers,

Daire

**Comment by daire-byrne** [comment] 2022-08-19 21:09
Just to add, I tried on v6.0-rc1 and got similar behaviour. If you just ctrl-c a running client rsync, the remote spawned rsync --daemon process does not exit and acts like it's still trying to communicate with the client.

I have added a timeout to the rsyncd config so that they die out after some idle period, but when using mptcp they are not detecting the closed client socket connection and gracefully exiting.

**Comment by pabeni** [comment] 2022-08-26 11:38
Hello, 

Thanks for the report.
I can reproduce the issue locally with a similar env.

I think there are (at least :() a couple of problems:
- in the describe scenario, tcp sends a reset, while mptcp sends a plain data_fin - it should use instead a fastclose.
- it looks like that on fastclose reception, we do not set/propagate correctly the socket error (should be ECONNRESET)

the 2nd issue is likely minor, as the rsync server should still hit a ENOTCON after receiving a fastclose and should still error-out. The first issue is likely causing the hang-out here.

We likely need to add more state processing to mptcp_close() to properly generate the fast close in the relevant scenario. Likely we need to replicate tcp_need_reset()/data_was_unread

**Comment by pabeni** [comment] 2022-08-26 17:12
I posted on the devel ML a change that should address your scenario (at least WFM):

https://lore.kernel.org/mptcp/fda2e5ce19891d50fc3b7cff19c81330b5b475b1.1661533333.git.pabeni@redhat.com/T/#u

@daire-byrne: Could you please double-check it works as expected for you, too?

**Comment by pabeni** [comment] 2022-08-26 17:13
Side note: we will need an additional patch to properly propagete the ECONNRESET error code at reset time (currently rsync sees an EPIPE)

**Comment by daire-byrne** [comment] 2022-08-28 21:04
Thanks Paolo! I tried to apply this to v6.0.0-rc2 and it applied okay but I'm getting some compile errors:

```
net/mptcp/protocol.c: In function 'mptcp_do_fastclose':
net/mptcp/protocol.c:2531:2: error: implicit declaration of function 'mptcp_for_each_subflow_safe'; did you mean 'mptcp_for_each_subflow'? [-Werror=implicit-function-declaration]
  mptcp_for_each_subflow_safe(msk, subflow, tmp)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  mptcp_for_each_subflow
net/mptcp/protocol.c:2531:48: error: expected ';' before '__mptcp_close_ssk'
  mptcp_for_each_subflow_safe(msk, subflow, tmp)
                                                ^
                                                ;
   __mptcp_close_ssk(sk, mptcp_subflow_tcp_sock(subflow),
```

I haven't had a chance to debug much further than that yet. Perhaps I'm missing some more dependant patched from net-next.

**Comment by pabeni** [comment] 2022-08-29 06:25
The patch is on top of the current export branch:

https://github.com/multipath-tcp/mptcp_net-next

it contains a few more mptcp-related commits WRT the current Linus vanilla tree, that will land there for around 6.1.

You can either checkout the above tree or I can share a version of the patch for 6.0. Please let me know

**Comment by daire-byrne** [comment] 2022-08-29 06:33
If it's not too much hassle, then a patch for v6.0 would be appreciated simply because we plan to run that in production.

But I will test with the mptcp_linux-net branch and report back....

**Comment by matttbe** [comment] 2022-08-29 08:48
@daire-byrne : on top of v6.0-rc2 and Paolo's patch, you can replace one line to have it working:

```diff
diff --git a/net/mptcp/protocol.c b/net/mptcp/protocol.c
index f2746bb6b761..7f9c949fa950 100644
--- a/net/mptcp/protocol.c
+++ b/net/mptcp/protocol.c
@@ -2528,7 +2528,7 @@ static void mptcp_do_fastclose(struct sock *sk)
        struct mptcp_subflow_context *subflow, *tmp;
        struct mptcp_sock *msk = mptcp_sk(sk);
 
-       mptcp_for_each_subflow_safe(msk, subflow, tmp)
+       list_for_each_entry_safe(subflow, tmp, &msk->conn_list, node)
                __mptcp_close_ssk(sk, mptcp_subflow_tcp_sock(subflow),
                                  subflow, MPTCP_CF_FASTCLOSE);
 }
```

(or you add this macro in the protocol.h file)
```c
#define mptcp_for_each_subflow_safe(__msk, __subflow, __tmp)                    \
        list_for_each_entry_safe(__subflow, __tmp, &((__msk)->conn_list), node)
```

**Comment by daire-byrne** [comment] 2022-08-30 09:42
Thanks both - I got it working in v6.0.0-rc2 and it looks like it has fixed the issue.

If I run an rsync from client to server and ctrl-c it on the client, I now see that the corresponding rsyncd spawned process on the server is responding correctly. In fact, we see it in the rsyncd log on the server now:

> 2022/08/30 10:35:57 [23720] rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at io.c(1644) [sender=3.2.3]

Many thanks!

**Comment by matttbe** [comment] 2022-09-21 12:44
Should be fixed now in our tree thanks to @pabeni 's patches:

New patches for t/upstream:
- 374cd727ed92: mptcp: propagate fastclose error
- c745856e931e: mptcp: use fastclose on more edge scenarios
- 7ed8005532f4: selftests: mptcp: update and extend fastclose test-cases
- Results: e4bedeb4fae3..fc5b36e8ab3d (export)

**Closed as completed by matttbe** 2022-09-21 12:44 UTC
Labels: enhancement
