### ISSUE TITLE
[syzkaller] divide error in __tcp_select_window

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#111] opened 2020-11-17 16:48 UTC
```
divide error: 0000 [#1] SMP KASAN
CPU: 1 PID: 10697 Comm: syz-executor.7 Not tainted 5.10.0-rc3 #42
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
RIP: 0010:__tcp_select_window+0x509/0xa60 net/ipv4/tcp_output.c:3008
Code: 44 89 ff e8 f9 e1 a9 fe 45 39 e7 0f 8d 20 ff ff ff e8 cb e0 a9 fe 44 89 e3 e9 13 ff ff ff e8 be e0 a9 fe 44 89 e0 44 89 e3 99 <f7> 7c 24 04 29 d3 e9 fc fe ff ff e8 a7 e0 a9 fe 44 89 f1 48 89 ea
RSP: 0018:ffffc90015af79d0 EFLAGS: 00010216
RAX: 0000000000000000 RBX: 0000000000000000 RCX: ffffc90002fcf000
RDX: 0000000000000000 RSI: ffffffff82908342 RDI: 0000000000000004
RBP: 0000000000000000 R08: ffff888020849880 R09: ffffed10060c4c42
R10: ffff88803062620b R11: ffffed10060c4c41 R12: 0000000000000000
R13: 1ffff92002b5ef3e R14: 0000000000000000 R15: 0000000000000000
FS:  00007f6a69d1d700(0000) GS:ffff88811b300000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 0000000000462960 CR3: 0000000107537003 CR4: 0000000000170ee0
Call Trace:
 tcp_cleanup_rbuf+0x37a/0x5a0 net/ipv4/tcp.c:1587
 mptcp_send_ack+0x154/0x1b0 net/mptcp/protocol.c:444
 mptcp_recvmsg+0x1012/0x1880 net/mptcp/protocol.c:1604
 inet_recvmsg+0x4f3/0x660 net/ipv4/af_inet.c:851
 sock_recvmsg_nosec net/socket.c:885 [inline]
 sock_recvmsg_nosec net/socket.c:882 [inline]
 sock_recvmsg net/socket.c:903 [inline]
 __sys_recvfrom+0x373/0x3e0 net/socket.c:2049
 __do_sys_recvfrom net/socket.c:2067 [inline]
 __se_sys_recvfrom net/socket.c:2063 [inline]
 __x64_sys_recvfrom+0xdd/0x1b0 net/socket.c:2063
 do_syscall_64+0x33/0x40 arch/x86/entry/common.c:46
 entry_SYSCALL_64_after_hwframe+0x44/0xa9
RIP: 0033:0x7f6a6964d469
Code: 00 f3 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d ff 49 2b 00 f7 d8 64 89 01 48
RSP: 002b:00007f6a69d1cdc8 EFLAGS: 00000246 ORIG_RAX: 000000000000002d
RAX: ffffffffffffffda RBX: 000000000069bfa8 RCX: 00007f6a6964d469
RDX: 0000000000020000 RSI: 00000000200000c0 RDI: 0000000000000003
RBP: 000000000069bfa8 R08: 0000000020000100 R09: 0000000000000010
R10: 0000000000000000 R11: 0000000000000246 R12: 000000000069bfb4
R13: 00007ffc5aa35c6f R14: 000000000041e4f0 R15: 0000000000000003
Modules linked in:
Dumping ftrace buffer:
   (ftrace buffer empty)
---[ end trace 220f9c7fb706a088 ]---
RIP: 0010:__tcp_select_window+0x509/0xa60 net/ipv4/tcp_output.c:3008
Code: 44 89 ff e8 f9 e1 a9 fe 45 39 e7 0f 8d 20 ff ff ff e8 cb e0 a9 fe 44 89 e3 e9 13 ff ff ff e8 be e0 a9 fe 44 89 e0 44 89 e3 99 <f7> 7c 24 04 29 d3 e9 fc fe ff ff e8 a7 e0 a9 fe 44 89 f1 48 89 ea
RSP: 0018:ffffc90015af79d0 EFLAGS: 00010216
RAX: 0000000000000000 RBX: 0000000000000000 RCX: ffffc90002fcf000
RDX: 0000000000000000 RSI: ffffffff82908342 RDI: 0000000000000004
RBP: 0000000000000000 R08: ffff888020849880 R09: ffffed10060c4c42
R10: ffff88803062620b R11: ffffed10060c4c41 R12: 0000000000000000
R13: 1ffff92002b5ef3e R14: 0000000000000000 R15: 0000000000000000
FS:  00007f6a69d1d700(0000) GS:ffff88811b300000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 0000000000462960 CR3: 0000000107537003 CR4: 0000000000170ee0
```

No reproducer yet.

HEAD is now at:
ee897d427e40 ("DO-NOT-MERGE: mptcp: enabled by default")  (HEAD, tag: export/20201117T153419, mptcp_net-next/export) (73 minutes ago) <Matthieu Baerts>
4d684bc86398 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (73 minutes ago) <Paolo Abeni>
9da10b09d9b8 ("mptcp: refine MPTCP-level ack scheduling")  (73 minutes ago) <Paolo Abeni>
4ee210bb9f9f ("mptcp: track window announced to peer")  (73 minutes ago) <Florian Westphal>
9cc35f64138d ("selftests: mptcp: add ADD_ADDR IPv6 test cases")  (73 minutes ago) <Geliang Tang>
e24ec9a88e57 ("mptcp: send out dedicated ADD_ADDR packet")  (73 minutes ago) <Geliang Tang>
df437e99dcad ("mptcp: change add_addr_signal type")  (73 minutes ago) <Geliang Tang>
ffa808791431 ("mptcp: keep unaccepted MPC subflow into join list")  (73 minutes ago) <Paolo Abeni>
7eebe9d88c8f ("selftests: mptcp: add link failure test case")  (73 minutes ago) <Florian Westphal>
8d2da75f8377 ("mptcp: skip to next candidate if subflow has unacked data")  (73 minutes ago) <Florian Westphal>
dbd904705c23 ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (73 minutes ago) <Nicolas Rybowski>
852fcb4ba54f ("bpf:selftests: add MPTCP test base")  (73 minutes ago) <Nicolas Rybowski>
4da060062aa4 ("bpf: add 'bpf_mptcp_sock' structure and helper")  (73 minutes ago) <Nicolas Rybowski>
5033765ee185 ("mptcp: attach subflow socket to parent cgroup")  (73 minutes ago) <Nicolas Rybowski>
4935ad7f138b ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (73 minutes ago) <Nicolas Rybowski>
72308ecbf33b ("Merge branch 'mptcp-improve-multiple-xmit-streams-support'")  (mptcp_net-next/net-next) (22 hours ago) <Jakub Kicinski>
7ed90803a213 ("mptcp: send explicit ack on delayed ack_seq incr")  (22 hours ago) <Paolo Abeni>
6f8a612a33e4 ("mptcp: keep track of advertised windows right edge")  (22 hours ago) <Florian Westphal>
8edf08649eed ("mptcp: rework poll+nospace handling")  (22 hours ago) <Florian Westphal>
813e0a683d4c ("mptcp: try to push pending data on snd una updates")  (22 hours ago) <Paolo Abeni>
d9ca1de8c0cd ("mptcp: move page frag allocation in mptcp_sendmsg()")  (22 hours ago) <Paolo Abeni>
e16163b6e2b7 ("mptcp: refactor shutdown and close")  (22 hours ago) <Paolo Abeni>
eaa2ffabfc35 ("mptcp: introduce MPTCP snd_nxt")  (22 hours ago) <Paolo Abeni>
f0e6a4cf11f1 ("mptcp: add accounting for pending data")  (22 hours ago) <Paolo Abeni>
caf971df01b8 ("mptcp: reduce the arguments of mptcp_sendmsg_frag")  (22 hours ago) <Paolo Abeni>
ba8f48f7a4d7 ("mptcp: introduce mptcp_schedule_work")  (22 hours ago) <Paolo Abeni>
77c3c9563752 ("tcp: factor out __tcp_close() helper")  (22 hours ago) <Paolo Abeni>
e2223995a287 ("mptcp: use tcp_build_frag()")  (22 hours ago) <Paolo Abeni>
b796d04bd014 ("tcp: factor out tcp_build_frag()")  (22 hours ago) <Paolo Abeni>
c0a645a7f944 ("Merge branch 'fix-inefficiences-and-rename-nla_strlcpy'")  (25 hours ago) <Jakub Kicinski>

**Comment by pabeni** [comment] 2020-11-23 12:30
It looks like Eric found the root cause behind this:

https://lore.kernel.org/netdev/ca0b65f8-7a69-ff4e-9e0d-66a7a923b0c1@gmail.com/

with just a glance...

**Comment by pabeni** [comment] 2020-11-26 16:15
fixed with:

commit fd8976790a6c1fee98bd7bc73754ddc9f01273ab
Author: Paolo Abeni <pabeni@redhat.com>
Date:   Tue Nov 24 22:51:24 2020 +0100

    mptcp: be careful on MPTCP-level ack.

**Closed as completed by pabeni** 2020-11-26 16:15 UTC
Labels: bug, syzkaller
