### ISSUE TITLE
[iproute2] endpoint add with "id" is not persisted

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#72] opened 2020-08-03 17:07 UTC
```
root@server:~/iproute2# ./ip/ip mptcp endpoint add 10.2.5.1 id 5 signal
root@server:~/iproute2# ./ip/ip mptcp endpoint show
10.2.3.1 id 1 signal
10.2.4.1 id 2 signal
10.2.5.1 id 3 signal
```

(btw., endpoint show also does not work - I will share a patch)

**Comment by pabeni** [comment] 2020-12-03 16:35
this is a duplicate of #117, closing this instance as work is being done on the other issue

**Closed as completed by pabeni** 2020-12-03 16:35 UTC
Labels: enhancement, iproute2
