### ISSUE TITLE
[syzkaller] divide error in tcp_write_xmit

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#219] opened 2021-07-29 15:24 UTC
```
RDX: 0000000000000058 RSI: 0000000020000700 RDI: 0000000000000003
RBP: 0000000000000001 R08: 0000000000000000 R09: 0000000000000000
R10: 0000000000000000 R11: 0000000000000246 R12: 000000000069bf8c
R13: 00007ffeec86bc8f R14: 00007fc5c2e7b000 R15: 0000000000000003
divide error: 0000 [#1] SMP KASAN
CPU: 1 PID: 15606 Comm: syz-executor.2 Not tainted 5.14.0-rc2dbcc212d6b0adbd170ae7c16e6ed7862e7c473fb #100
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
RIP: 0010:tcp_tso_autosize net/ipv4/tcp_output.c:1975 [inline]
RIP: 0010:tcp_tso_segs net/ipv4/tcp_output.c:1992 [inline]
RIP: 0010:tcp_write_xmit+0x1f1/0x5e20 net/ipv4/tcp_output.c:2623
Code: d0 7c 08 84 d2 0f 85 4b 32 00 00 41 8b 86 f4 01 00 00 49 8d be 06 02 00 00 48 89 f9 2d c1 00 00 00 48 39 d8 48 0f 47 c3 31 d2 <f7> 34 24 48 ba 00 00 00 00 00 fc ff df 39 e8 0f 43 e8 48 c1 e9 03
RSP: 0018:ffffc90008ba7818 EFLAGS: 00010246
RAX: 000000000000ff3f RBX: 0000000000ca3ca9 RCX: ffff88810aee5c06
RDX: 0000000000000000 RSI: ffffffff828f641f RDI: ffff88810aee5c06
RBP: 0000000000000002 R08: 00000000000249ef R09: 0000000000000001
R10: ffffffff829efe80 R11: 0000000000000007 R12: 0000000000000000
R13: ffff88810aee5ec8 R14: ffff88810aee5a00 R15: 0000000000000001
FS:  00007fc5c2e9b700(0000) GS:ffff88811b500000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 00007fc5c272fa90 CR3: 0000000104d74002 CR4: 0000000000170ee0
Call Trace:
 __tcp_push_pending_frames+0xaa/0x320 net/ipv4/tcp_output.c:2874
 tcp_push+0x44f/0x6d0 net/ipv4/tcp.c:736
 mptcp_push_release net/mptcp/protocol.c:1493 [inline]
 __mptcp_push_pending+0x4c9/0x710 net/mptcp/protocol.c:1557
 mptcp_sendmsg+0x150c/0x1a50 net/mptcp/protocol.c:1751
 inet_sendmsg+0x115/0x140 net/ipv4/af_inet.c:824
 sock_sendmsg_nosec net/socket.c:703 [inline]
 sock_sendmsg net/socket.c:723 [inline]
 sock_write_iter+0x40a/0x4d0 net/socket.c:1056
 call_write_iter include/linux/fs.h:2114 [inline]
 new_sync_write+0x432/0x660 fs/read_write.c:518
 vfs_write+0x60c/0x810 fs/read_write.c:605
 ksys_write+0x1df/0x240 fs/read_write.c:658
 do_syscall_x64 arch/x86/entry/common.c:50 [inline]
 do_syscall_64+0x3b/0x90 arch/x86/entry/common.c:80
 entry_SYSCALL_64_after_hwframe+0x44/0xae
RIP: 0033:0x7fc5c27aa469
Code: 00 f3 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d ff 49 2b 00 f7 d8 64 89 01 48
RSP: 002b:00007fc5c2e9ada8 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
RAX: ffffffffffffffda RBX: 0000000000000001 RCX: 00007fc5c27aa469
RDX: 0000000000000058 RSI: 0000000020000700 RDI: 0000000000000003
RBP: 0000000000000001 R08: 0000000000000000 R09: 0000000000000000
R10: 0000000000000000 R11: 0000000000000246 R12: 000000000069bf8c
R13: 00007ffeec86bc8f R14: 00007fc5c2e7b000 R15: 0000000000000003
Modules linked in:
---[ end trace bc99ed3aad29c89c ]---
RIP: 0010:tcp_tso_autosize net/ipv4/tcp_output.c:1975 [inline]
RIP: 0010:tcp_tso_segs net/ipv4/tcp_output.c:1992 [inline]
RIP: 0010:tcp_write_xmit+0x1f1/0x5e20 net/ipv4/tcp_output.c:2623
Code: d0 7c 08 84 d2 0f 85 4b 32 00 00 41 8b 86 f4 01 00 00 49 8d be 06 02 00 00 48 89 f9 2d c1 00 00 00 48 39 d8 48 0f 47 c3 31 d2 <f7> 34 24 48 ba 00 00 00 00 00 fc ff df 39 e8 0f 43 e8 48 c1 e9 03
RSP: 0018:ffffc90008ba7818 EFLAGS: 00010246
RAX: 000000000000ff3f RBX: 0000000000ca3ca9 RCX: ffff88810aee5c06
RDX: 0000000000000000 RSI: ffffffff828f641f RDI: ffff88810aee5c06
RBP: 0000000000000002 R08: 00000000000249ef R09: 0000000000000001
R10: ffffffff829efe80 R11: 0000000000000007 R12: 0000000000000000
R13: ffff88810aee5ec8 R14: ffff88810aee5a00 R15: 0000000000000001
FS:  00007fc5c2e9b700(0000) GS:ffff88811b500000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 00007fc5c272fa90 CR3: 0000000104d74002 CR4: 0000000000170ee0
```

HEAD:
ab492b0cda37 ("DO-NOT-MERGE: mptcp: enabled by default")  (HEAD, tag: export/20210811T054647) (6 days ago) <Matthieu Baerts>
ae04382d2db0 ("DO-NOT-MERGE: mptcp: add CI support")  (6 days ago) <Matthieu Baerts>
41cdd20cf8d3 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (6 days ago) <Paolo Abeni>
b48a74dab069 ("DO-NOT-MERGE: git markup: features other trees")  (6 days ago) <Matthieu Baerts>
71101e54b80f ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (6 days ago) <Nicolas Rybowski>
dd94ccb2dcd3 ("bpf:selftests: add MPTCP test base")  (6 days ago) <Nicolas Rybowski>
6133a36543a5 ("bpf: add 'bpf_mptcp_sock' structure and helper")  (6 days ago) <Nicolas Rybowski>
516a4c37e96e ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (6 days ago) <Nicolas Rybowski>
fcfc01310b2b ("DO-NOT-MERGE: git markup: features net-next")  (6 days ago) <Matthieu Baerts>
02955aaac54e ("selftests: mptcp: add MP_FAIL mibs check")  (6 days ago) <Geliang Tang>
19dc19777227 ("mptcp: add the mibs for MP_FAIL")  (6 days ago) <Geliang Tang>
c7795f2730cd ("mptcp: send out MP_FAIL when data checksum fails")  (6 days ago) <Geliang Tang>
ea60cfb55e5d ("mptcp: MP_FAIL suboption receiving")  (6 days ago) <Geliang Tang>
eadcd1a68012 ("mptcp: MP_FAIL suboption sending")  (6 days ago) <Geliang Tang>
64d92fc0cf68 ("selftests: mptcp: delete uncontinuous removing ids")  (6 days ago) <Geliang Tang>
fb6297ab33f9 ("selftests: mptcp: add fullmesh testcases")  (6 days ago) <Geliang Tang>
7572e8676ce3 ("selftests: mptcp: set and print the fullmesh flag")  (6 days ago) <Geliang Tang>
c834af3957d3 ("mptcp: local addresses fullmesh")  (6 days ago) <Geliang Tang>
8366f8186def ("mptcp: remote addresses fullmesh")  (6 days ago) <Geliang Tang>
5fe9c6598fda ("mptcp: drop flags and ifindex arguments")  (6 days ago) <Geliang Tang>
f9794f81754c ("mptcp: shrink mptcp_out_options struct")  (6 days ago) <Paolo Abeni>
74567e840b6f ("mptcp: optimize out option generation")  (6 days ago) <Paolo Abeni>
e9f447341749 ("selftests: mptcp: add_addr and echo race test")  (6 days ago) <Yonglong Li>
c1154300fe94 ("mptcp: remove MPTCP_ADD_ADDR_IPV6 and MPTCP_ADD_ADDR_PORT")  (6 days ago) <Yonglong Li>
8884df555ff6 ("mptcp: build ADD_ADDR/echo-ADD_ADDR option according pm.add_signal")  (6 days ago) <Yonglong Li>
14629cdf199f ("mptcp: fix ADD_ADDR and RM_ADDR maybe flush addr_signal each other")  (6 days ago) <Yonglong Li>
8e82e4e8e9d8 ("mptcp: make MPTCP_ADD_ADDR_SIGNAL and MPTCP_ADD_ADDR_ECHO separate")  (6 days ago) <Yonglong Li>
208455ced406 ("mptcp: move drop_other_suboptions check under pm lock")  (6 days ago) <Yonglong Li>
dab6dacf6a0c ("selftests: mptcp: add testcase for active-back")  (6 days ago) <Paolo Abeni>
35076924bdab ("mptcp: backup flag from incoming MPJ ack option")  (6 days ago) <Paolo Abeni>
504d723feabc ("mptcp: add mibs for stale subflows processing")  (6 days ago) <Paolo Abeni>
c403f0b958ad ("mptcp: faster active backup recovery")  (6 days ago) <Paolo Abeni>
604533ee96ee ("mptcp: cleanup sysctl data and helpers")  (6 days ago) <Paolo Abeni>
2353aae3b8a4 ("mptcp: handle pending data on closed subflow")  (6 days ago) <Paolo Abeni>
910dc9e86542 ("mptcp: less aggressive retransmission strategy")  (6 days ago) <Paolo Abeni>
e3d92f9cabf8 ("mptcp: more accurate timeout")  (6 days ago) <Paolo Abeni>
3b0580f5f564 ("DO-NOT-MERGE: git markup: fixes net-next")  (6 days ago) <Matthieu Baerts>
bbc092f430f2 ("DO-NOT-MERGE: git markup: fixes net")  (6 days ago) <Matthieu Baerts>
eb35486685c1 ("DO-NOT-MERGE: git markup: fixes other trees")  (6 days ago) <Matthieu Baerts>
faf5b8b5866c ("DO-NOT-MERGE: git markup: net-next")  (6 days ago) <Matthieu Baerts>
d3432bf10f17 ("net: Support filtering interfaces on no master")  (6 days ago) <Lahav Schlesinger>
a5397d68b2db ("net/sched: cls_api, reset flags on replay")  (6 days ago) <Mark Bloch>
ebd0d30cc5e4 ("Merge branch 'mlx5-next' of git://git.kernel.org/pub/scm/linux/kernel/git/mellanox/linux")  (6 days ago) <Jakub Kicinski>

No reproducer

[UPDATE 8/16: Updated HEAD]

**Comment by pabeni** [comment] 2021-07-30 09:44
@martineau: I can exclude this could be cause by:

 mptcp: optimize out option generation
or
 mptcp: move drop_other_suboptions check under pm lock

@cpaasch: if you are able somehow trigger this issue, can you please try the following debug patch:
```
diff --git a/net/mptcp/protocol.c b/net/mptcp/protocol.c
index 8eb2626503d7..e4585333c4d4 100644
--- a/net/mptcp/protocol.c
+++ b/net/mptcp/protocol.c
@@ -1294,6 +1294,8 @@ static int mptcp_sendmsg_frag(struct sock *sk, struct sock *ssk,
 
        /* compute send limit */
        info->mss_now = tcp_send_mss(ssk, &info->size_goal, info->flags);
+       if (!info->mss_now)
+               pr_warn("mss cache=%d tcp_header_len=%d", tcp_sk(ssk)->mss_cache, tcp_sk(ssk)->tcp_header_len);
        avail_size = info->size_goal;
        skb = tcp_write_queue_tail(ssk);
        if (skb) {
```

**Comment by matttbe** [comment] 2021-08-05 18:42
@mjmartineau : By chance, do you have his syskaller issue on your side as well?
Because Christoph will not be able to look at that this week.

**Comment by mjmartineau** [comment] 2021-08-05 20:30
@matttbe I've never seen this one in my syzkaller setup

**Comment by matttbe** [comment] 2021-08-06 10:13
@mjmartineau  Thank you for having looked! Probably a different syzkaller config!

**Comment by cpaasch** [comment] 2021-08-12 15:08
I have no reproducer for this issue and up to now it has only happened once. So, seems pretty rare or it has disappeared.

**Comment by mjmartineau** [comment] 2021-08-19 15:23
syzkaller just found something that might be similar, has happened 3 times:

```
divide error: 0000 [#1] SMP KASAN NOPTI
CPU: 1 PID: 12465 Comm: syz-executor.1 Not tainted 5.14.0-rc5+ #1
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.13.0-1ubuntu1.1 04/01/2014
RIP: 0010:__tcp_select_window+0x509/0xa60 net/ipv4/tcp_output.c:3016
Code: 44 89 ff e8 d9 65 e9 fd 45 39 e7 0f 8d 20 ff ff ff e8 eb 64 e9 fd 44 89 e3 e9 13 ff ff ff e8 de 64 e9 fd 44 89 e0 44 89 e3 99 <f7> 7c 24 04 29 d3 e9 fc fe ff ff e8 c7 64 e9 fd 44 89 f1 48 89 ea
RSP: 0018:ffff88803b117020 EFLAGS: 00010212
RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000040000
RDX: 0000000000000000 RSI: ffff888037544080 RDI: 0000000000000002
RBP: 0000000000000000 R08: ffffffff8357ca72 R09: 0000000000000000
R10: 0000000000000004 R11: ffffed1005024c41 R12: 0000000000000000
R13: 1ffff11007622e08 R14: 0000000000000000 R15: 0000000000000000
FS:  00007efedf6e7700(0000) GS:ffff88811af00000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 0000001b2f022000 CR3: 000000001b398002 CR4: 0000000000770ee0
PKRU: 55555554
Call Trace:
 tcp_select_window net/ipv4/tcp_output.c:264 [inline]
 __tcp_transmit_skb+0xc00/0x37a0 net/ipv4/tcp_output.c:1351
 __tcp_send_ack.part.0+0x3ec/0x760 net/ipv4/tcp_output.c:3971
 __tcp_send_ack net/ipv4/tcp_output.c:3977 [inline]
 tcp_send_ack+0x7d/0xa0 net/ipv4/tcp_output.c:3977
 mptcp_pm_nl_addr_send_ack+0x1ab/0x380 net/mptcp/pm_netlink.c:654
 mptcp_pm_remove_addr+0x161/0x200 net/mptcp/pm.c:58
 mptcp_nl_remove_id_zero_address+0x197/0x460 net/mptcp/pm_netlink.c:1328
 mptcp_nl_cmd_del_addr+0x98b/0xd40 net/mptcp/pm_netlink.c:1359
 genl_family_rcv_msg_doit.isra.0+0x225/0x340 net/netlink/genetlink.c:731
 genl_family_rcv_msg net/netlink/genetlink.c:775 [inline]
 genl_rcv_msg+0x341/0x5b0 net/netlink/genetlink.c:792
 netlink_rcv_skb+0x148/0x430 net/netlink/af_netlink.c:2504
 genl_rcv+0x24/0x40 net/netlink/genetlink.c:803
 netlink_unicast_kernel net/netlink/af_netlink.c:1314 [inline]
 netlink_unicast+0x537/0x750 net/netlink/af_netlink.c:1340
 netlink_sendmsg+0x846/0xd80 net/netlink/af_netlink.c:1929
 sock_sendmsg_nosec net/socket.c:704 [inline]
 sock_sendmsg+0x14e/0x190 net/socket.c:724
 ____sys_sendmsg+0x709/0x870 net/socket.c:2403
 ___sys_sendmsg+0xff/0x170 net/socket.c:2457
 __sys_sendmsg+0xe5/0x1b0 net/socket.c:2486
 do_syscall_x64 arch/x86/entry/common.c:50 [inline]
 do_syscall_64+0x38/0x90 arch/x86/entry/common.c:80
 entry_SYSCALL_64_after_hwframe+0x44/0xae
RIP: 0033:0x469dbd
Code: 02 b8 ff ff ff ff c3 66 0f 1f 44 00 00 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 c7 c1 bc ff ff ff f7 d8 64 89 01 48
RSP: 002b:00007efedf6e6c58 EFLAGS: 00000246 ORIG_RAX: 000000000000002e
RAX: ffffffffffffffda RBX: 000000000057bf80 RCX: 0000000000469dbd
RDX: 0000000000000000 RSI: 0000000020000640 RDI: 0000000000000004
RBP: 00000000004d4cd5 R08: 0000000000000000 R09: 0000000000000000
R10: 0000000000000000 R11: 0000000000000246 R12: 000000000057bf80
R13: 00007ffe0c43203f R14: 00007ffe0c4321e0 R15: 00007efedf6e6dc0
Modules linked in:
---[ end trace 60ab1bcf16c5b12e ]---
RIP: 0010:__tcp_select_window+0x509/0xa60 net/ipv4/tcp_output.c:3016
Code: 44 89 ff e8 d9 65 e9 fd 45 39 e7 0f 8d 20 ff ff ff e8 eb 64 e9 fd 44 89 e3 e9 13 ff ff ff e8 de 64 e9 fd 44 89 e0 44 89 e3 99 <f7> 7c 24 04 29 d3 e9 fc fe ff ff e8 c7 64 e9 fd 44 89 f1 48 89 ea
RSP: 0018:ffff88803b117020 EFLAGS: 00010212
RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000040000
RDX: 0000000000000000 RSI: ffff888037544080 RDI: 0000000000000002
RBP: 0000000000000000 R08: ffffffff8357ca72 R09: 0000000000000000
R10: 0000000000000004 R11: ffffed1005024c41 R12: 0000000000000000
R13: 1ffff11007622e08 R14: 0000000000000000 R15: 0000000000000000
FS:  00007efedf6e7700(0000) GS:ffff88811af00000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 0000001b2f022000 CR3: 000000001b398002 CR4: 0000000000770ee0
PKRU: 55555554
```

Kernel code: export/20210817T164404

**Comment by mjmartineau** [comment] 2021-08-19 15:30
@pabeni Earliest `__tcp_select_divide()` error was 8 August, stack traces are the same all three times.

**Comment by pabeni** [comment] 2021-08-20 14:33
@mjmartineau: could you please try if the following patch solve the issue:
```
diff --git a/net/ipv4/route.c b/net/ipv4/route.c
index b181773d7ad3..34bba90c0fee 100644
--- a/net/ipv4/route.c
+++ b/net/ipv4/route.c
@@ -3547,7 +3547,8 @@ static struct ctl_table ipv4_route_table[] = {
                .data           = &ip_rt_min_advmss,
                .maxlen         = sizeof(int),
                .mode           = 0644,
-               .proc_handler   = proc_dointvec,
+               .proc_handler   = proc_dointvec_minmax,
+               .extra1         = &ip_min_valid_pmtu,
        },
        { }
 };
diff --git a/net/ipv6/route.c b/net/ipv6/route.c
index 6cf4bb89ca69..59d022c46958 100644
--- a/net/ipv6/route.c
+++ b/net/ipv6/route.c
@@ -6273,6 +6273,8 @@ static int rt6_stats_seq_show(struct seq_file *seq, void *v)
 
 #ifdef CONFIG_SYSCTL
 
+static int ipv6_min_mss __ro_after_init                = TCP_MIN_MSS;
+
 static int ipv6_sysctl_rtcache_flush(struct ctl_table *ctl, int write,
                              void *buffer, size_t *lenp, loff_t *ppos)
 {
@@ -6354,7 +6356,8 @@ static struct ctl_table ipv6_route_table_template[] = {
                .data           =       &init_net.ipv6.sysctl.ip6_rt_min_advmss,
                .maxlen         =       sizeof(int),
                .mode           =       0644,
-               .proc_handler   =       proc_dointvec,
+               .proc_handler   =       proc_dointvec_minmax,
+               .extra1         =       &ipv6_min_mss,
        },
        {
                .procname       =       "gc_min_interval_ms",

```

**Comment by mjmartineau** [comment] 2021-08-20 18:11
@pabeni Do you still want me to try the min ~MTU~ MSS patch above, or is [your patch on the mailing list](https://patchwork.kernel.org/project/mptcp/patch/286de8f451b32f60e75d3b8bcc4df515e186b930.1629481305.git.pabeni@redhat.com/) the better one to be testing now?

**Comment by pabeni** [comment] 2021-08-23 11:05
> @pabeni Do you still want me to try the min MTU patch above, or is [your patch on the mailing list](https://patchwork.kernel.org/project/mptcp/patch/286de8f451b32f60e75d3b8bcc4df515e186b930.1629481305.git.pabeni@redhat.com/) the better one to be testing now?

I think there are different root causes/issues coming into place here. The posted patch should address a real issue, but not related to any of the call trace reported here. The change proposed here could possibly address the root cause for the issue/backtrace reported by you. So I kindly ask you to run syzkaller on the above. I don't think the patch posted on the ML will affect your case.

**Comment by mjmartineau** [comment] 2021-08-23 23:55
@pabeni Ok, running the above changes with current 2021-08-23 export branch. Syzkaller didn't catch any more divide-by-zero errors running with 2f9bf3d80ffe7f23896df4ed9848358eb84f1e73 `mptcp: fix possible divide by zero` over the weekend.

**Comment by mjmartineau** [comment] 2021-08-25 16:43
Saw the same syzkaller error twice last night - tag export/20210824T164010 (43e735f7eccb151acc4dc85d0cfc6fb970ddd50d) plus @pabeni's suggestion above. Exactly the same stack trace.

**Comment by mjmartineau** [comment] 2021-08-25 17:31
I think the error I'm seeing might be happening when the PM tries to send an ADD_ADDR before a subflow is fully initialized. `mptcp_pm_nl_addr_send_ack()` grabs the first subflow off of conn_list and calls `tcp_send_ack()` on it without checking the connection state.

Might be only a mptcp-next thing after adding fullmesh? I'll likely split this in to a separate bug.

**Comment by mjmartineau** [comment] 2021-08-25 22:26
Separating the `mptcp_pm_nl_addr_send_ack()` error in to a new issue, #229

**Comment by matttbe** [comment] 2021-08-26 13:46
This #219 issue should be fixed thanks to patches from Paolo:
- 5d8855f6a71f: mptcp: fix possible divide by zero
- Results: 84fc11b83a29..653135eedf64
- 56344a303b57: "squashed" in "mptcp: fix possible divide by zero"
- Results: e4be38126ede..d9f4bc9e6463

Builds and tests:
- https://cirrus-ci.com/github/multipath-tcp/mptcp_net-next/export/20210824T100358
- https://github.com/multipath-tcp/mptcp_net-next/actions/workflows/build-validation.yml?query=branch:export/20210824T100358

**Closed as completed by matttbe** 2021-08-26 13:46 UTC
Labels: bug, syzkaller
