### ISSUE TITLE
[syzkaller] WARNING in sk_stream_kill_queues

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#136] opened 2021-01-14 19:07 UTC
Similar/same to #115 but I couldn't repro that one with the existing reproducer. So, opening a new issue. @dcaratti 

```
TCP: request_sock_subflow: Possible SYN flooding on port 20000. Sending cookies.  Check SNMP counters.
TCP: request_sock_subflow: Possible SYN flooding on port 20000. Sending cookies.  Check SNMP counters.
------------[ cut here ]------------
WARNING: CPU: 0 PID: 12 at net/core/stream.c:208 sk_stream_kill_queues+0x3ca/0x530 net/core/stream.c:208
Modules linked in:
CPU: 0 PID: 12 Comm: kworker/0:1 Not tainted 5.11.0-rc2 #59
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
Workqueue: events mptcp_worker
RIP: 0010:sk_stream_kill_queues+0x3ca/0x530 net/core/stream.c:208
Code: 03 0f b6 04 02 84 c0 74 08 3c 03 0f 8e 63 01 00 00 8b ab 00 01 00 00 e9 60 ff ff ff e8 2f 24 d3 fe 0f 0b eb 97 e8 26 24 d3 fe <0f> 0b eb a0 e8 1d 24 d3 fe 0f 0b e9 a5 fe ff ff 4c 89 e7 e8 0e d0
RSP: 0018:ffffc900000c7bc8 EFLAGS: 00010293
RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
RDX: ffff88810030ac40 RSI: ffffffff8262ca4a RDI: 0000000000000003
RBP: 0000000000000d00 R08: 0000000000000000 R09: ffffffff85095aa7
R10: ffffffff8262c9ea R11: 0000000000000001 R12: ffff888108908100
R13: ffffffff85095aa0 R14: ffffc900000c7c48 R15: 1ffff92000018f85
FS:  0000000000000000(0000) GS:ffff88811b200000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 00007fa7444baef8 CR3: 0000000035ee9005 CR4: 0000000000170ef0
Call Trace:
 __mptcp_destroy_sock+0x4a7/0x6c0 net/mptcp/protocol.c:2547
 mptcp_worker+0x7dd/0x1610 net/mptcp/protocol.c:2272
 process_one_work+0x896/0x1170 kernel/workqueue.c:2275
 worker_thread+0x605/0x1350 kernel/workqueue.c:2421
 kthread+0x344/0x410 kernel/kthread.c:292
 ret_from_fork+0x22/0x30 arch/x86/entry/entry_64.S:296
```

HEAD:
0ba8e381319a ("mptcp: fix locking in mptcp_disconnect()")  (HEAD) (3 hours ago) <Paolo Abeni>
2231a14a0d42 ("DO-NOT-MERGE: mptcp: enabled by default")  (tag: export/20210114T060000, mptcp_net-next/export) (13 hours ago) <Matthieu Baerts>
bdb95de71fe6 ("DO-NOT-MERGE: mptcp: add GitHub Actions")  (13 hours ago) <Matthieu Baerts>
37e13d6e5600 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (13 hours ago) <Paolo Abeni>
89c6174b783e ("mptcp: schedule work for better snd subflow selection")  (13 hours ago) <Paolo Abeni>
e61bdd4536e3 ("mptcp: do not queue excessive data on subflows")  (13 hours ago) <Paolo Abeni>
22a5014b0c10 ("mptcp: re-enable sndbuf autotune")  (13 hours ago) <Paolo Abeni>
5ec4e3d81ae3 ("mptcp: always graft subflow socket to parent")  (13 hours ago) <Paolo Abeni>
c7a8b478d036 ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (13 hours ago) <Nicolas Rybowski>
4aad7af6b076 ("bpf:selftests: add MPTCP test base")  (13 hours ago) <Nicolas Rybowski>
71880f981f7f ("bpf: add 'bpf_mptcp_sock' structure and helper")  (13 hours ago) <Nicolas Rybowski>
197e7ab42147 ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (13 hours ago) <Nicolas Rybowski>
127854a8dd50 ("linux: handle MPTCP consistently with TCP")  (13 hours ago) <Paolo Abeni>
fe5b34dc31e8 ("mptcp: better msk-level shutdown.")  (13 hours ago) <Paolo Abeni>
cdca68586d28 ("mptcp: more strict state checking for acks")  (13 hours ago) <Paolo Abeni>
0ae5b43d6dde ("tcp: assign skb hash after tcp_event_data_sent")  (mptcp_net-next/net-next) (15 hours ago) <Yuchung Cheng>

No reproducer.

CONFIG-file:
[CONFIG.txt](https://github.com/multipath-tcp/mptcp_net-next/files/5816464/CONFIG.txt)

**Comment by cpaasch** [comment] 2021-01-22 17:46
@pabeni : Here is the additional logging:

```
------------[ cut here ]------------
sk->sk_forward_alloc is 3328
WARNING: CPU: 0 PID: 12645 at net/core/stream.c:208 sk_stream_kill_queues+0x3e0/0x550 net/core/stream.c:208
Modules linked in:
CPU: 0 PID: 12645 Comm: kworker/0:3 Not tainted 5.11.0-rc4 #60
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
Workqueue: events mptcp_worker
RIP: 0010:sk_stream_kill_queues+0x3e0/0x550 net/core/stream.c:208
Code: df e8 34 0c fc ff e9 64 ff ff ff e8 8a f5 d2 fe 0f 0b e9 b2 fe ff ff e8 7e f5 d2 fe 89 ee 48 c7 c7 40 1b 4c 83 e8 06 6e 54 00 <0f> 0b eb b6 e8 67 f5 d2 fe 89 ee 48 c7 c7 00 1b 4c 83 e8 ef 6d 54
RSP: 0018:ffffc900014afbc8 EFLAGS: 00010282
RAX: 0000000000000000 RBX: ffff88801ff19000 RCX: 0000000000000000
RDX: ffff888020203b00 RSI: ffffffff8121cb73 RDI: fffff52000295f6b
RBP: 0000000000000d00 R08: 0000000000000001 R09: 0000000000000000
R10: ffffffff8140222f R11: 0000000000000000 R12: ffff88801ff19100
R13: ffff88801ff190b0 R14: ffffc900014afc48 R15: 1ffff92000295f85
FS:  0000000000000000(0000) GS:ffff88811b200000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 0000001b2df23000 CR3: 00000000195e1003 CR4: 0000000000170ef0
Call Trace:
 __mptcp_destroy_sock+0x4ac/0x6c0 net/mptcp/protocol.c:2536
 mptcp_worker+0x7d1/0x1300 net/mptcp/protocol.c:2259
 process_one_work+0x896/0x1170 kernel/workqueue.c:2275
 worker_thread+0x605/0x1350 kernel/workqueue.c:2421
 kthread+0x344/0x410 kernel/kthread.c:292
 ret_from_fork+0x22/0x30 arch/x86/entry/entry_64.S:296
```

HEAD is:
368136a629e9 ("some more debugging in sk_stream_kill_queues")  (HEAD) (25 hours ago) <Christoph Paasch>
e593f49c374a ("DO-NOT-MERGE: mptcp: enabled by default")  (tag: export/20210121T064902, mptcp_net-next/export) (35 hours ago) <Matthieu Baerts>
5867bf94a556 ("DO-NOT-MERGE: mptcp: add GitHub Actions")  (35 hours ago) <Matthieu Baerts>
e78642876387 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (35 hours ago) <Paolo Abeni>
63b65bbc1716 ("mptcp: move pm netlink work into pm_netlink")  (35 hours ago) <Florian Westphal>
488e396bc46e ("mptcp: pm: add lockdep assertions")  (35 hours ago) <Florian Westphal>
e945e76329a7 ("selftests: mptcp: add command line arguments for mptcp_join.sh")  (35 hours ago) <Geliang Tang>
e72d05769ebc ("selftests: mptcp: add testcases for ADD_ADDR with port")  (35 hours ago) <Geliang Tang>
512bb17f727d ("mptcp: add the mibs for ADD_ADDR with port")  (35 hours ago) <Geliang Tang>
cb119364be83 ("selftests: mptcp: add port argument for pm_nl_ctl")  (35 hours ago) <Geliang Tang>
c2ed22300cb5 ("mptcp: deal with MPTCP_PM_ADDR_ATTR_PORT in PM netlink")  (35 hours ago) <Geliang Tang>
602ff2ca148e ("mptcp: enable use_port when invoke addresses_equal")  (35 hours ago) <Geliang Tang>
1428417b8a10 ("mptcp: add port number check for MP_JOIN")  (35 hours ago) <Geliang Tang>
b512e2f5fcd7 ("mptcp: add a new helper subflow_req_create_thmac")  (35 hours ago) <Geliang Tang>
74f27e4ef1c0 ("mptcp: drop unused skb in subflow_token_join_request")  (35 hours ago) <Geliang Tang>
6791f0aa0391 ("mptcp: create the listening socket for new port")  (35 hours ago) <Geliang Tang>
0049736608aa ("selftests: mptcp: add testcases for newly added addresses")  (35 hours ago) <Geliang Tang>
2dab81018858 ("selftests: mptcp: use minus values for removing address numbers")  (35 hours ago) <Geliang Tang>
f8ed6abc51bc ("mptcp: create subflow or signal addr for newly added address")  (35 hours ago) <Geliang Tang>
7621646118fd ("mptcp: drop *_max fields in mptcp_pm_data")  (35 hours ago) <Geliang Tang>
38a01ce64bde ("mptcp: use WRITE_ONCE/READ_ONCE for the pernet *_max")  (35 hours ago) <Geliang Tang>
de8c81b6edd0 ("selftests: increase timeout to 10 min")  (35 hours ago) <Matthieu Baerts>
95124029a80a ("selftests: mptcp: add IPv4-mapped IPv6 testcases")  (35 hours ago) <Geliang Tang>
61e71b7ec2cd ("mptcp: pm nl: reduce variable scope")  (35 hours ago) <Matthieu Baerts>
9b9ede93a559 ("mptcp: pm nl: support IPv4 mapped in v6 addresses")  (35 hours ago) <Matthieu Baerts>
10983545d868 ("mptcp: support MPJoin with IPv4 mapped in v6 sk")  (35 hours ago) <Matthieu Baerts>
dc8f6f5cab5c ("mptcp: implement delegated actions")  (35 hours ago) <Paolo Abeni>
3ce2165ce029 ("mptcp: schedule work for better snd subflow selection")  (35 hours ago) <Paolo Abeni>
f8fe15347262 ("mptcp: do not queue excessive data on subflows")  (35 hours ago) <Paolo Abeni>
827d13c127c7 ("mptcp: re-enable sndbuf autotune")  (35 hours ago) <Paolo Abeni>
0a22d00f3516 ("mptcp: always graft subflow socket to parent")  (35 hours ago) <Paolo Abeni>
647033cb4c8f ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (35 hours ago) <Nicolas Rybowski>
e06a9f914f3b ("bpf:selftests: add MPTCP test base")  (35 hours ago) <Nicolas Rybowski>
415b9de01039 ("bpf: add 'bpf_mptcp_sock' structure and helper")  (35 hours ago) <Nicolas Rybowski>
f3f73ff3cfd6 ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (35 hours ago) <Nicolas Rybowski>
1645be411570 ("linux: handle MPTCP consistently with TCP")  (35 hours ago) <Paolo Abeni>
d29aee6062f3 ("Merge branch 'net-inline-rollback_registered-functions'")  (mptcp_net-next/net-next) (2 days ago) <Jakub Kicinski>

CONFIG-file: 
[CONFIG.txt](https://github.com/multipath-tcp/mptcp_net-next/files/5857591/CONFIG.txt)

**Comment by pabeni** [comment] 2021-01-26 18:31
> @pabeni : Here is the additional logging:
> ------------[ cut here ]------------
> sk->sk_forward_alloc is 3328
> WARNING: CPU: 0 PID: 12645 at net/core/stream.c:208 sk_stream_kill_queues+0x3e0/0x550 net/core/stream.c:208

So it looks like we have a left-over packet somewhere... but I can't find any possible left-over/race by code inspection.
@cpaasch: could you please add a similar debug patch for __mptcp_destroy_sock() to dump rmem_released/wmem_reserved?

**Comment by matttbe** [comment] 2021-01-28 11:33
Could it be linked to https://lkml.org/lkml/2020/11/30/120 ? With a patch here: https://lkml.org/lkml/2020/12/10/1025
But the patch is not in net-next from what I see.

**Comment by cpaasch** [comment] 2021-01-28 18:32
We have a reproducer!!!

```
# {Threaded:false Collide:false Repeat:true RepeatTimes:0 Procs:1 Slowdown:1 Sandbox: Fault:true FaultCall:3 FaultNth:7 Leak:false NetInjection:false NetDevices:false NetReset:false Cgroups:false BinfmtMisc:false CloseFDs:false KCSAN:false DevlinkPCI:false USB:false VhciInjection:false Wifi:false Sysctl:false UseTmpDir:false HandleSegv:false Repro:false Trace:false}
r0 = socket$inet_mptcp(0x2, 0x1, 0x106)
bind$inet(r0, &(0x7f00000013c0)={0x2, 0x4e20, @multicast2}, 0x10)
connect$inet(r0, &(0x7f0000000040)={0x2, 0x4e20, @loopback}, 0x4d)
write$binfmt_aout(r0, 0x0, 0x1420)
```

**Comment by cpaasch** [comment] 2021-01-28 21:50
And... with Eric's patch, the syzkaller does not trigger anymore.

**Comment by matttbe** [comment] 2021-01-29 15:40
@cpaasch thank you for having tested!

Is it OK to close this ticket or do you prefer to wait for Eric patch landing in the net-next tree?
I can also add his patch in our tree, maybe easier.

Could you eventually reply with a "Tested-by" to Eric if you don't mind? :)
https://lore.kernel.org/netdev/CANn89i+2mAu_srdvefKLDY23HvrbOG1aMfj5uwvk6tYZ9uBtMA@mail.gmail.com/

**Comment by cpaasch** [comment] 2021-02-01 16:48
It has just been posted: https://patchwork.kernel.org/project/netdevbpf/patch/20210201160420.2826895-1-elver@google.com/

**Comment by cpaasch** [comment] 2021-02-02 16:56
Actually, no! The problem still happened! It just took syzkaller a few days to find it...

**Comment by cpaasch** [comment] 2021-02-09 17:42
Reproducer:

```
# {Threaded:false Collide:false Repeat:true RepeatTimes:0 Procs:1 Slowdown:1 Sandbox:none Fault:true FaultCall:5 FaultNth:9 Leak:false NetInjection:false NetDevices:true NetReset:false Cgroups:false BinfmtMisc:false CloseFDs:true KCSAN:false DevlinkPCI:false USB:false VhciInjection:false Wifi:false Sysctl:false UseTmpDir:false HandleSegv:false Repro:false Trace:false}
r0 = socket$inet_mptcp(0x2, 0x1, 0x106)
bind$inet(r0, &(0x7f00000013c0)={0x2, 0x4e20}, 0x10)
listen(r0, 0x0)
r1 = socket$inet_mptcp(0x2, 0x1, 0x106)
connect$inet(r1, &(0x7f0000000040)={0x2, 0x4e20, @remote}, 0x10)
sendmmsg(r1, &(0x7f00000007c0)=[{{0x0, 0x0, &(0x7f00000011c0)=[{&(0x7f00000002c0)='w', 0x10002}], 0x1}}], 0x1, 0x0)
```

HEAD:
af8e85128b4d ("Revert "DO-NOT-MERGE: mptcp: use kmalloc on kasan build"")  (25 hours ago) <Christoph Paasch>
4a71543af897 ("mptcp: init mptcp request socket earlier")  (25 hours ago) <Paolo Abeni>
87ccece4131d ("mptcp: fix spurious retransmissions")  (25 hours ago) <Paolo Abeni>
a15e2853f271 ("DO-NOT-MERGE: mptcp: enabled by default")  (tag: export/20210207T062839) (2 days ago) <Matthieu Baerts>
119c5bb36193 ("DO-NOT-MERGE: mptcp: add GitHub Actions")  (2 days ago) <Matthieu Baerts>
8e5ec861d555 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (2 days ago) <Paolo Abeni>
238d6b531aa0 ("mptcp: add local addr info in mptcp_info")  (2 days ago) <Geliang Tang>
928f65de3af7 ("mptcp: fix poll after shutdown")  (2 days ago) <Paolo Abeni>
e0d489bf056c ("mptcp: deliver ssk errors to msk")  (2 days ago) <Paolo Abeni>
4e78a50aaa41 ("mptcp: add netlink event support")  (2 days ago) <Florian Westphal>
c267230ffe9e ("genetlink: add CAP_NET_ADMIN test for multicast bind")  (2 days ago) <Florian Westphal>
1afc248cecb6 ("mptcp: avoid lock_fast usage in accept path")  (2 days ago) <Florian Westphal>
3a90f9b35714 ("mptcp: pass subflow socket to a few helpers")  (2 days ago) <Florian Westphal>
ac2f5294b8b7 ("mptcp: move subflow close loop after sk close check")  (2 days ago) <Florian Westphal>
8099dadd54e1 ("mptcp: schedule worker when subflow is closed")  (2 days ago) <Florian Westphal>
57feb111110c ("mptcp: split __mptcp_close_ssk helper")  (2 days ago) <Florian Westphal>
a2043deaa5f0 ("mptcp: move pm netlink work into pm_netlink")  (2 days ago) <Florian Westphal>
02f0a519c040 ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (2 days ago) <Nicolas Rybowski>
6512eb1e17d4 ("bpf:selftests: add MPTCP test base")  (2 days ago) <Nicolas Rybowski>
1e8a1ee7e58c ("bpf: add 'bpf_mptcp_sock' structure and helper")  (2 days ago) <Nicolas Rybowski>
d439d5d2adbb ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (2 days ago) <Nicolas Rybowski>
ae3cb866a5ee ("linux: handle MPTCP consistently with TCP")  (2 days ago) <Paolo Abeni>
badc6ac32122 ("Merge branch '100GbE' of git://git.kernel.org/pub/scm/linux/kernel/git/tnguy/next-queue")  (3 days ago) <Jakub Kicinski>

kernel-config:
[Uploading CONFIG.txt…]()

**Comment by fw-strlen** [comment] 2021-02-15 13:50
Failed to reproduce this in ~30k iterations on  ee378cef2b4ccfbb96b113026b71443c670219ab (tag: export/20210214T063313)

**Comment by cpaasch** [comment] 2021-02-19 16:30
Still happening... :-/

HEAD:
b118cc0dfad9 ("DO-NOT-MERGE: mptcp: enabled by default")  (HEAD, tag: export/20210218T061505, mptcp_net-next/export) (34 hours ago) <Matthieu Baerts>
afb39359cfee ("DO-NOT-MERGE: mptcp: add GitHub Actions")  (34 hours ago) <Matthieu Baerts>
fb66148f9fc7 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (34 hours ago) <Paolo Abeni>
ab09cf34d769 ("selftests: mptcp: add testcases for removing addrs")  (34 hours ago) <Geliang Tang>
26f4ca25f1cc ("selftests: mptcp: set addr id for removing testcases")  (34 hours ago) <Geliang Tang>
b16c8fa93783 ("selftests: mptcp: add invert argument for chk_rm_nr")  (34 hours ago) <Geliang Tang>
5fb7c01b6bd0 ("mptcp: remove a list of addrs when flushing")  (34 hours ago) <Geliang Tang>
84f5b2871836 ("mptcp: remove multi addresses and subflows in PM")  (34 hours ago) <Geliang Tang>
1343f2e1cadd ("mptcp: remove multi subflows in PM")  (34 hours ago) <Geliang Tang>
f78ff7200e22 ("mptcp: remove multi addresses in PM")  (34 hours ago) <Geliang Tang>
8be112ebada0 ("mptcp: add rm_list_rx in mptcp_pm_data")  (34 hours ago) <Geliang Tang>
ad3cbaebf3db ("mptcp: add rm_list in mptcp_options_received")  (34 hours ago) <Geliang Tang>
ad2399b36e79 ("mptcp: add rm_list_tx in mptcp_pm_data")  (34 hours ago) <Geliang Tang>
783bf0f20379 ("mptcp: add rm_list in mptcp_out_options")  (34 hours ago) <Geliang Tang>
d66e0832f257 ("mptcp: drop unused subflow in mptcp_pm_subflow_established")  (34 hours ago) <Geliang Tang>
da0ff1038c19 ("mptcp: fix DATA_FIN generation on early shutdown")  (34 hours ago) <Paolo Abeni>
1956a17cd676 ("mptcp: clean-up the rtx path")  (34 hours ago) <Paolo Abeni>
3a90e26fb18d ("mptcp: fix race in release_cb")  (34 hours ago) <Paolo Abeni>
08d4b3614aa0 ("mptcp: factor out __mptcp_retrans helper()")  (34 hours ago) <Paolo Abeni>
fb4bec1924c4 ("mptcp: dispose initial struct socket when its subflow is closed")  (34 hours ago) <Florian Westphal>
f5ddfd379165 ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (34 hours ago) <Nicolas Rybowski>
c31680c18d06 ("bpf:selftests: add MPTCP test base")  (34 hours ago) <Nicolas Rybowski>
a03c346dc061 ("bpf: add 'bpf_mptcp_sock' structure and helper")  (34 hours ago) <Nicolas Rybowski>
b183b48da869 ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (34 hours ago) <Nicolas Rybowski>
849dea57117f ("linux: handle MPTCP consistently with TCP")  (34 hours ago) <Paolo Abeni>
194cb4e96385 ("x86/build: Disable CET instrumentation in the kernel for 32-bit too")  (34 hours ago) <Borislav Petkov>
3bec5cb51783 ("mptcp: fix DATA_FIN processing for orphaned sockets")  (34 hours ago) <Paolo Abeni>
85b8c8d3ef4f ("mptcp: provide subflow aware release function")  (34 hours ago) <Florian Westphal>
c1e8864231ba ("mptcp: reset last_snd on subflow close")  (34 hours ago) <Florian Westphal>
38b5133ad607 ("octeontx2-pf: Fix otx2_get_fecparam()")  (mptcp_net-next/net-next) (2 days ago) <Dan Carpenter>

CONFIG-file: 
[CONFIG.txt](https://github.com/multipath-tcp/mptcp_net-next/files/6011413/CONFIG.txt)

syzkaller-repro:
```
# {Threaded:false Collide:false Repeat:true RepeatTimes:0 Procs:1 Slowdown:1 Sandbox:none Fault:true FaultCall:5 FaultNth:8 Leak:false NetInjection:false NetDevices:true NetReset:false Cgroups:false BinfmtMisc:false CloseFDs:true KCSAN:false DevlinkPCI:false USB:false VhciInjection:false Wifi:false Sysctl:false UseTmpDir:false HandleSegv:false Repro:false Trace:false}
r0 = socket$inet_mptcp(0x2, 0x1, 0x106)
bind$inet(r0, &(0x7f00000013c0)={0x2, 0x4e20}, 0x10)
listen(r0, 0x0)
r1 = socket$inet_mptcp(0x2, 0x1, 0x106)
connect$inet(r1, &(0x7f0000000040)={0x2, 0x4e20, @remote}, 0x10)
writev(r1, &(0x7f0000001280)=[{&(0x7f0000000080)="5450fc7d778f08e22bb9da4c904bb761cc66683bb5349cd1304af1144e833810550a2dd13583eaa754192d95f7759780d52b4e92cfdd93d03fec58019184614e7adfda58c8221a0522b54cef74d5bd7f85589d537416ca7563a432ecc7684e46164523534d5849a169ea7b0f1cd0aa0def1dc481382cfc851e7e70c88c6b9860ef47c6495ebfac63533dedb9d130e4393a15b03efe51ff81e43ad1e2a1d8096a276a369976a16d1cf7c04757041d6742545651105dd8146da831f10c8fa46e2791cf22a8fb72d3f54f10ceff1324e6d094", 0x1ff60}, {&(0x7f0000000180)="f66436bc8fb6d0b2a166f52b91d6d4dcce4f8095c14eb363d117968c14f397179c05a50d9c6864a9e02ed98bc960d1e5316132a0e9ca339a77ee4bf917ccd4e58a2e4af7a9b4913c8cb9d4e26366cc3853547898f89d0636be4c22376a05ae99e0f0112fee20cb03d5680292df1bbd27f776780fd0436cd3ee27bb57e7a3624811d53cacab019425e6f5d1cdf4f053ea507410061b5266db9c85b2c1dd2fcba15ec488cd331ab1272420fcfd0eb7f5656343c572f353f4330fe5e9874441b6aa85ed896457be30f2423f8939dd95e7b2901a340ca7b15a63d02665a5c978a3e4733fe98b91c734eac4acaeb273bd998d7e24c7e75f1b3a7284a68c73345ebeb66fcd9ebe00667d82075454166c06c54cea1683ebc36dd45990d7c102a0e1e91c501b1e8cda3ae0a3bff193c376dbe47a003bea548f242ddc0c1f6bdcd790699dfcc0a0f088031e93f9b679844301ae4cdb7738372bd881b5c009b3962413dcd0abc43d104681f374e026027c142a5915e08a4a3f39c9158204a3fd2200028412a14b296ce72434e07b07f80fa8e420dad719b76865854d25709d569e335d2b091eed4641500d66b45fd59508cc0a000024496bdde760b0a89dbba0d2295d49c442f713055e4b5585b8703463671e9a7ecca0f2ac1aa3aea4c8ffbe0f927be85cc95a9098b1d99d21cb1e6c7ceaeccbf13cbce152750dd651ba6fba9ed0373fd1b97baae665d0e4c7de1d067bbafaa81c751c30f2fbee1f4eb2ec8d8e2b1c44c49dea986725945075319a42e96cd67b60bdbd38164c2191e5c02734e819c7eb415315a893858130bc817a47fdabf938650fd0b5ef01570232b8e0860ed6bae4a4b01234c8edfb8b231cb534456cf8f0ab1f2b59fe5efae5c48b76b3166fac41f61b8697e7a79d72f5b1dd2ec782d1e8b574d4eb12361abeaccec70010dc7ccaab092210601df7c1dade4580ba04ff957f5d96853fde57442500810c000d7ba4e1f035785afdb2638611a04e80ede684403bbb06e448cb1f43ac73c81c06ca67ab53094c9eadafc894999accb200e56539d0da60acea17b53aa67edf4aabb68d2ab5c58a146d2635fb71b76dc855c59ca2157fed9d3a5904f3acc7a54bbd70a42d0aff8187b02ce0618d3c256b2312cfd5", 0x330}], 0x2)
```

C-reproducer:
[repro.c.txt](https://github.com/multipath-tcp/mptcp_net-next/files/6011426/repro.c.txt)

**Comment by cpaasch** [comment] 2021-02-19 16:43
I am able to reproduce with the C-prog.

**Closed as completed** 2021-02-23 08:14 UTC
Labels: bug, syzkaller
