### ISSUE TITLE
Some newly added endpoints won't be used to create subflows on an existing MPTCP connection

### ISSUE THREAD

**Issue by arinc9** [multipath-tcp/mptcp_net-next#510] opened 2024-07-17 12:38 UTC
Tested on `next-20240712` with non-MPTCP related changes running on client and server. Exact tree for reference https://github.com/arinc9/linux/commits/test-on-linuxnext/.

MPTCP is supposed to establish subflows on already created MPTCP connections, using endpoints that were put on the MPTCP endpoint table after the MPTCP connection was created. Currently, this doesn't work properly. We have three endpoints. Only one of these endpoints will be established as a subflow on an already created MPTCP connection.

```
# nmcli c up telkom
# nmcli c down fibre
# nmcli c down mtn
# mptcpize run openvpn --config /etc/openvpn/client.ovpn &
[         CREATED] token=65742cb3 remid=0 locid=0 saddr4=100.102.176.135 daddr4=102.132.169.219 sport=37794 dport=1194
[     ESTABLISHED] token=65742cb3 remid=0 locid=0 saddr4=100.102.176.135 daddr4=102.132.169.219 sport=37794 dport=1194
[...]
```

`mtk_soc_eth` (ethernet) network interface, `eth1`:

```
# nmcli c up fibre
[  SF_ESTABLISHED] token=65742cb3 remid=0 locid=8 saddr4=192.168.11.252 daddr4=102.132.169.219 sport=43329 dport=1194 backup=0 ifindex=3
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/331)
```

`cdc_mbim` (wwan) network interface, `wwu1u2i4`:

```
# nmcli c up mtn
[ 2606.718466] 8021q: adding VLAN 0 to HW filter on device wwu1u2i4
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/36)
```

This issue happens on both wwan interfaces, `wwu1u2i4` and `wwu1u3i4`. Packet captures listening on `wwu1u2i4` and `wwu1u3i4` show that no MPTCP packets, specifically no join connection packets are sent on these interfaces.

MPTCP is supposed to establish subflows using the endpoints described on the MPTCP endpoint table which can be seen with the "`ip mptcp endpoint`" command. When creating an MPTCP connection, subflows will be established using these endpoints. Currently, this works properly. When creating an MPTCP connection, all of the endpoints will be used to create subflows.

```
# killall openvpn; mptcpize run openvpn --config /etc/openvpn/client.ovpn &
[          CLOSED] token=65742cb3
[...]
[         CREATED] token=0759ed3e remid=0 locid=0 saddr4=41.147.200.22 daddr4=102.132.169.219 sport=42762 dport=1194
[     ESTABLISHED] token=0759ed3e remid=0 locid=0 saddr4=41.147.200.22 daddr4=102.132.169.219 sport=42762 dport=1194
[  SF_ESTABLISHED] token=0759ed3e remid=0 locid=10 saddr4=192.168.11.252 daddr4=102.132.169.219 sport=50191 dport=1194 backup=0 ifindex=3
[  SF_ESTABLISHED] token=0759ed3e remid=0 locid=11 saddr4=100.102.176.135 daddr4=102.132.169.219 sport=50357 dport=1194 backup=0 ifindex=14
[...]
```

On both sides:

```
# ip mp l
add_addr_accepted 0 subflows 3 

# sysctl net.mptcp.pm_type
net.mptcp.pm_type = 0
```

**Comment by pabeni** [comment] 2024-07-17 13:33
@arinc9: can you please show the endpoints configuration (`ip mptcp endpoint`) and the full socket stat (`ss -MeinmO`) before and after enabling the wwan link?

I suspect NM is creating many 'unneeded' endpoints (e.g. for for ipv6 addresess?!? ) that 'consume' the available subflow count

**Comment by arinc9** [comment] 2024-07-17 13:54
@pabeni thanks for looking over this quickly!

With all three connections up:

```
# ip -6 mp e
41.147.200.22 id 9 subflow dev wwu1u3i4 
192.168.11.252 id 10 subflow dev eth1 
100.102.176.135 id 11 subflow dev wwu1u2i4 
```

ss on client side won't show the MPTCP sockets for some reason. I'm using Buildroot 2024.05.1:

```
# ss -MeinmO
State    Recv-Q    Send-Q       Local Address:Port         Peer Address:Port    

# ss -tani
State    Recv-Q   Send-Q       Local Address:Port           Peer Address:Port                                                                                   
LISTEN   0        0               127.0.0.54:53                  0.0.0.0:*       rto:1 cwnd:10 ssthresh:5 reordering:0                                          
LISTEN   0        0               127.0.0.53:53                  0.0.0.0:*       rto:1 cwnd:10 ssthresh:5 reordering:0                                          
LISTEN   0        0                  0.0.0.0:5355                0.0.0.0:*       rto:1 cwnd:10 ssthresh:5 reordering:0                                          
LISTEN   0        0                  0.0.0.0:22                  0.0.0.0:*       rto:1 cwnd:10 ssthresh:5 reordering:0                                          
ESTAB    0        46           41.147.200.22:53084       102.132.169.219:1194    rto:0.45 ato:0.04 qack:15 bidir cwnd:10 reordering:0                           
ESTAB    0        0           192.168.11.252:55431       102.132.169.219:1194    rto:0.21 ato:0.04 qack:15 bidir cwnd:10 reordering:0                           
ESTAB    0        0          100.102.176.135:51633       102.132.169.219:1194    rto:0.27 cwnd:10 reordering:0                                                  
LISTEN   0        0                        *:5355                      *:*       rto:1 cwnd:10 ssthresh:5 reordering:0                                          
LISTEN   0        0                        *:22                        *:*       rto:1 cwnd:10 ssthresh:5 reordering:0                                          
```

Server side whilst only fibre and one wwan path is up:

```
$ sudo ss -MeinmO
State                Recv-Q                Send-Q                                 Local Address:Port                                 Peer Address:Port                 Process                
ESTAB                0                     0                                    102.132.169.219:1194                                41.147.200.22:34304                 ino:309320 sk:2002 cgroup:/system.slice/system-openvpn\x2dserver.slice/openvpn-server@server.service <-> skmem:(r0,rb131072,t0,tb50176,f0,w0,o0,bl0,d0) subflows:1 subflows_max:3 remote_key token:80b6b548 write_seq:453d893230dbceeb snd_una:453d893230dbceeb rcv_nxt:4c58b320faa271b9
```


Server side after the remaining wwan path is enabled:

```
$ sudo ss -MeinmO
State                Recv-Q                Send-Q                                 Local Address:Port                                 Peer Address:Port                 Process                
ESTAB                0                     0                                    102.132.169.219:1194                                41.147.200.22:34304                 ino:309320 sk:2002 cgroup:/system.slice/system-openvpn\x2dserver.slice/openvpn-server@server.service <-> skmem:(r0,rb131072,t0,tb50176,f0,w0,o0,bl0,d1) subflows:1 subflows_max:3 remote_key token:80b6b548 write_seq:453d893230dbde8d snd_una:453d893230dbde8d rcv_nxt:4c58b320faa281e9
```

Server side whilst the three paths are in use:

```
$ sudo ss -MeinmO
State                Recv-Q                Send-Q                                 Local Address:Port                                 Peer Address:Port                 Process                
ESTAB                0                     0                                    102.132.169.219:1194                                41.147.200.22:53084                 ino:305696 sk:1001 cgroup:/system.slice/system-openvpn\x2dserver.slice/openvpn-server@server.service <-> skmem:(r0,rb131072,t0,tb137216,f0,w0,o0,bl0,d0) subflows:2 subflows_max:3 remote_key token:edd956e write_seq:31f6d46f1a34b075 snd_una:31f6d46f1a34b075 rcv_nxt:8b9b15677b9a6397
```

**Comment by pabeni** [comment] 2024-07-17 15:18
It looks like we can exclude the scenario tripping on unwanted endpoints.

Unfortunately that also means that rooting down the issue will be difficult. So far I can't reproduce it locally, and the scenario is also covered by (non failing) selft-tests. 

Could you please add some probes to your running kernel to properly track the events on up?
something alike:

```
perf probe -a __mptcp_subflow_connect
perf probe -a 'select_local_address%return $retval'
perf probe -a mptcp_pm_create_subflow_or_signal_addr
perf probe -a 'kernel_connect%return $retval'
perf record -ag -e probe:__mptcp_subflow_connect -e probe select_local_address__return - e probe:kernel_connect__return -e mptcp_pm_create_subflow_or_signal_addr nmcli c up mtn
perf script
```

You can likely get even more detailed info with ftrace, but I can't guide you there ;)

The fact that the additional subflows are established when the mptcp socket is created after the link up makes me wonder about a possible routing issue? perhaps NM is creating the endpoint before creating the route associated with the new address???

**Comment by pabeni** [comment] 2024-07-18 09:37
> The fact that the additional subflows are established when the mptcp socket is created after the link up makes me wonder about a possible routing issue? perhaps NM is creating the endpoint before creating the route associated with the new address???

I talked with NM people and they tend to exclude such possibility, anyhow enabling trace level log in the NM conf should prove that (including verbose messages for each action taken by NM). You can do that adding

`level=TRACE`

in the `[logging]` section of  `/etc/NetworkManager/NetworkManager.conf`

**Comment by matttbe** [comment] 2024-07-18 16:09
@arinc9 : just to be on the safe side: do you have the same issue with the subflows client limit set to 8? And did you check without the firewall?

> Packet captures listening on wwu1u2i4 and wwu1u3i4 show that no MPTCP packets, specifically no join connection packets are sent on these interfaces.

Can you create "regular" TCP connections using these interfaces? Maybe the firewall or something else is blocking them.

Thank you, Paolo, for having looked!

@arinc9 The perf output would be ideal. If it is causing too many troubles, an alternative might be to use the [dynamic debug](https://www.kernel.org/doc/html/latest/admin-guide/dynamic-debug-howto.html) feature (it requires a kernel config, please see the doc if it doesn't work):

```
echo "func mptcp_pm_create_subflow_or_signal_addr +fmp" > /sys/kernel/debug/dynamic_debug/control
echo "func __mptcp_subflow_connect +fmp" > /sys/kernel/debug/dynamic_debug/control
```

Reproduce the issue, then check the kernel logs (dmesg).

(or with ftrace):

```
echo __mptcp_subflow_connect >> /sys/kernel/debug/tracing/set_ftrace_filter
echo mptcp_pm_create_subflow_or_signal_addr >> /sys/kernel/debug/tracing/set_ftrace_filter
echo function > /sys/kernel/debug/tracing/current_tracer
<reproduce the issue>
cat /sys/kernel/debug/tracing/trace
```

The issue with `ss` is strange: which version are you using? The one from IPRoute2? Do you know if the kernel has been compiled with `CONFIG_INET_DIAG` and `CONFIG_INET_MPTCP_DIAG`? (I don't know if OpenWRT enables the second one, they should if MPTCP and INET_DIAG/INET_TCP_DIAG are enabled)

**Comment by arinc9** [comment] 2024-07-19 13:33
@pabeni [NetworkManagerTrace.txt](https://github.com/user-attachments/files/16312532/NetworkManagerTrace.txt). I can't tell if the endpoint is added before the default route with metric is added. What do you see?

I've used `pr_info()` to trace the code path, https://github.com/arinc9/linux/commit/9043963808259463553d9ead903ae97d16374aaa.

`kernel_bind()` exits with return code -99. Once this happens, removing the endpoint and then adding it back results in `select_local_address()` failing. Therefore, a subflow won't ever be created using this endpoint on the existing MPTCP connection. I suppose this is an MPTCP bug.

```
# nmcli c up telkom
[   97.513087] MPTCP: check if should create a new subflow
[   97.513087] msk->pm.local_addr_used: 0, local_addr_max: 2
[   97.513087] msk->pm.subflows: 0, subflows_max: 3
[   97.528315] MPTCP: local_addr_used 0: saddr 192.168.11.252: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[   97.539444] MPTCP: local_addr_used 0: saddr 41.147.194.139: select_local_address() successful
[   97.547998] MPTCP: saddr 41.147.194.139: __mptcp_subflow_connect() ran
[   97.554552] MPTCP: saddr 41.147.194.139: kernel_bind() failed with code -99
[   97.561566] MPTCP: local_addr_used 1: saddr 192.168.11.252: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[   97.572693] MPTCP: local_addr_used 1: saddr 41.147.194.139: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[   97.583810] MPTCP: select_local_address() failed
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/10)
# ip mp e
192.168.11.252 id 2 subflow dev eth1 
41.147.194.139 id 3 subflow dev wwu1u3i4 
# ip r
default via 192.168.11.1 dev eth1 proto dhcp src 192.168.11.252 metric 101 
default via 41.147.194.140 dev wwu1u3i4 proto static metric 700 
[...]
# ip mp e d i 3
# ip mp e a 41.147.194.139 id 3 subflow dev wwu1u3i4 
[  118.693517] MPTCP: check if should create a new subflow
[  118.693517] msk->pm.local_addr_used: 1, local_addr_max: 2
[  118.693517] msk->pm.subflows: 0, subflows_max: 3
[  118.708755] MPTCP: local_addr_used 1: saddr 192.168.11.252: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  118.719882] MPTCP: local_addr_used 1: saddr 41.147.194.139: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  118.731001] MPTCP: select_local_address() failed
```

> The issue with ss is strange: which version are you using? The one from IPRoute2? Do you know if the kernel has been compiled with CONFIG_INET_DIAG and CONFIG_INET_MPTCP_DIAG? (I don't know if OpenWRT enables the second one, they should if MPTCP and INET_DIAG/INET_TCP_DIAG are enabled)

@matttbe I don't use OpenWrt to be able to use a custom kernel. I use Buildroot for the rootfs image, and the kernel image and device tree binary produced using the next-20240712 tree. So I maintain my own defconfig. CONFIG_INET_DIAG was not selected. Once I selected it - which, with it, CONFIG_INET_MPTCP_DIAG came selected as well - I was able to see the MPTCP sockets.

**Comment by matttbe** [comment] 2024-07-19 14:04
> `kernel_bind()` exits with return code -99.

That's `EADDRNOTAVAIL` (`Cannot assign requested address`). Could it be because you don't have such address locally? Or not at that specific time (maybe NM adds the endpoints first?)

(`sysctl -w net.ipv4.ip_nonlocal_bind=1` could prevent this issue I think, but best to understand why you have it.)

That's strange, because your endpoint has a "device".

Maybe can you try to find the reason why you have this error? If I'm not mistaken, it is set in `__inet_bind()`, maybe you can check in which state you are by adding some debug in `inet_addr_valid_or_nonlocal()`?

If you manage the endpoints manually, do you have the issue? Maybe NM adds the MPTCP endpoints while they are not ready yet?

Maybe Paolo has other ideas? :)

> Once this happens, removing the endpoint and then adding it back results in `select_local_address()` failing.

That's another issue, it should be fixed with [this patch](https://patchwork.kernel.org/project/mptcp/patch/20240719-mptcp-pm-avail-v3-8-e96b5591ced3@kernel.org/), probably best not to focus on that for the moment.

> Once I selected it - which, with it, CONFIG_INET_MPTCP_DIAG came selected as well - I was able to see the MPTCP sockets.

:+1:

**Comment by arinc9** [comment] 2024-07-19 15:23
> (sysctl -w net.ipv4.ip_nonlocal_bind=1 could prevent this issue I think, but best to understand why you have it.)

That does prevent it but now `kernel_connect()` fails with code -101.

I'll see to your suggestion and do further debugging in `inet_addr_valid_or_nonlocal()`.

**Comment by arinc9** [comment] 2024-07-20 13:37
@matttbe I'm running the export tree with the v3 of "mptcp: fix inconsistent backup usage" and v3 of "mptcp: fix endpoints with 'signal' and 'subflow' flags" patch series applied. The current debug changes are https://github.com/arinc9/linux/commit/4efbe665a8d139990b7b22045c388f5bce4860a3.

```
# nmcli c up telkom
[  163.062631] 8021q: adding VLAN 0 to HW filter on device wwu1u3i4
[  163.073967] MPTCP: check if should create a new subflow
[  163.073967] msk->pm.local_addr_used: 0, local_addr_max: 2
[  163.073967] msk->pm.subflows: 1, subflows_max: 3
[  163.089200] MPTCP: local_addr_used 0: saddr 192.168.11.252: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  163.100323] MPTCP: local_addr_used 0: saddr 41.146.68.141: select_local_address() successful
[  163.108756] MPTCP: saddr 41.146.68.141: __mptcp_subflow_connect() ran
[  163.115222] IPv4: running inet_addr_valid_or_nonlocal()
[  163.120436] IPv4: addr_type == RTN_UNICAST
[  163.124567] IPv4: saddr 41.146.68.141: inet_addr_valid_or_nonlocal() returned zero, __inet_bind() failed
[  163.134053] MPTCP: saddr 41.146.68.141: kernel_bind() failed with code -99
[  163.140942] MPTCP: local_addr_used 1: saddr 192.168.11.252: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  163.152065] MPTCP: local_addr_used 1: saddr 41.146.68.141: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  163.163095] MPTCP: select_local_address() failed
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/14)
```

With `net.ipv4.ip_nonlocal_bind=1`:

```
# sysctl -w net.ipv4.ip_nonlocal_bind=1
net.ipv4.ip_nonlocal_bind = 1
# [  183.191430] IPv4: running inet_addr_valid_or_nonlocal()
[  183.196671] IPv4: inet_can_nonlocal_bind(net, inet) is true
[  183.202231] IPv4: addr == htonl(INADDR_ANY)
[  183.206410] IPv4: addr_type == RTN_BROADCAST
[  183.210668] IPv4: saddr 0.0.0.0: inet_addr_valid_or_nonlocal() returned non-zero, __inet_bind() succesful
nmcli c up telkom
[  204.438727] 8021q: adding VLAN 0 to HW filter on device wwu1u3i4
[  204.450157] MPTCP: check if should create a new subflow
[  204.450157] msk->pm.local_addr_used: 0, local_addr_max: 2
[  204.450157] msk->pm.subflows: 1, subflows_max: 3
[  204.465385] MPTCP: local_addr_used 0: saddr 192.168.11.252: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  204.476511] MPTCP: local_addr_used 0: saddr 41.146.68.141: select_local_address() successful
[  204.484942] MPTCP: saddr 41.146.68.141: __mptcp_subflow_connect() ran
[  204.491403] IPv4: running inet_addr_valid_or_nonlocal()
[  204.496617] IPv4: inet_can_nonlocal_bind(net, inet) is true
[  204.502183] IPv4: addr_type == RTN_UNICAST
[  204.506267] IPv4: saddr 41.146.68.141: inet_addr_valid_or_nonlocal() returned non-zero, __inet_bind() succesful
[  204.516359] MPTCP: saddr 41.146.68.141: kernel_connect() failed with code -101
[  204.523597] MPTCP: local_addr_used 1: saddr 192.168.11.252: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  204.534717] MPTCP: local_addr_used 1: saddr 41.146.68.141: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  204.545746] MPTCP: select_local_address() failed
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/15)
```

Re-adding the endpoint:

```
# ip mp e
192.168.11.252 id 4 subflow dev eth1 
41.146.68.141 id 5 subflow dev wwu1u3i4 
# ip mp e d i 5
# ip mp e a 41.146.68.141 id 5 subflow dev wwu1u3i4 
[  283.723324] MPTCP: check if should create a new subflow
[  283.723324] msk->pm.local_addr_used: 0, local_addr_max: 2
[  283.723324] msk->pm.subflows: 1, subflows_max: 3
[  283.738549] MPTCP: local_addr_used 0: saddr 192.168.11.252: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  283.749673] MPTCP: local_addr_used 0: saddr 41.146.68.141: select_local_address() successful
[  283.758110] MPTCP: saddr 41.146.68.141: __mptcp_subflow_connect() ran
[  283.764566] IPv4: running inet_addr_valid_or_nonlocal()
[  283.769784] IPv4: inet_can_nonlocal_bind(net, inet) is true
[  283.775348] IPv4: addr_type == RTN_LOCAL
[  283.779258] IPv4: saddr 41.146.68.141: inet_addr_valid_or_nonlocal() returned non-zero, __inet_bind() succesful
[  283.789411] MPTCP: local_addr_used 1: saddr 192.168.11.252: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  283.800532] MPTCP: local_addr_used 1: saddr 41.146.68.141: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  283.811561] MPTCP: select_local_address() failed
# [  SF_ESTABLISHED] token=ecb59374 remid=0 locid=5 saddr4=41.146.68.141 daddr4=102.132.169.219 sport=50039 dport=1194 backup=0 ifindex=9
```

It looks like the `RTN_UNICAST` type is given to the IPv4 address assigned to the interface first, then it's set to `RTN_LOCAL`. It seems NetworkManager adds the endpoint early enough for this race condition to appear. This must be a kernel bug, no? No userspace programme should catch the kernel at this state.

**Comment by matttbe** [comment] 2024-07-22 08:52
@arinc9 thank you for the new tests.

To me, it **looks** like NM is adding the endpoints too quickly, when they cannot be used yet. I **think** that they should wait before adding them, and not the kernel that should check the state, wait, and retry later.

In NM logs, we can see that the MPTCP endpoint is added on line 331, but the route is added later (around lines 429-441?), no? I'm not familiar to these logs.

@pabeni : WDYT?

**Comment by pabeni** [comment] 2024-07-22 10:36
> @arinc9 thank you for the new tests.
> 
> To me, it **looks** like NM is adding the endpoints too quickly, when they cannot be used yet. I **think** that they should wait before adding them, and not the kernel that should check the state, wait, and retry later.
> 
> In NM logs, we can see that the MPTCP endpoint is added on line 331, but the route is added later (around lines 429-441?), no? I'm not familiar to these logs.
> 
> @pabeni : WDYT?

I agree with @matttbe: it looks like NM is adding endpoints too early. Let me cycle back to the NM team.

**Comment by pabeni** [comment] 2024-07-22 11:17
I just filed a NM issue WRT the above behavior:

https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/1583

**Comment by pabeni** [comment] 2024-07-22 11:23
@arinc9: Beniamino Galvani from the NM crew suggests as possible workaround to try disabling the ipv4 duplicate address detection: `ipv4.dad-timeout 0` in the NM conf. That should move the address creation earlier, and could possibly mitigate the issue.

**Comment by arinc9** [comment] 2024-07-22 12:52
@pabeni Yup, that does indeed mitigate the issue. Should I close this issue as it has nothing to do with the kernel?

```
# nmcli c up telkom
[  204.855260] 8021q: adding VLAN 0 to HW filter on device wwu1u3i4
[  204.867189] MPTCP: check if should create a new subflow
[  204.867189] msk->pm.local_addr_used: 1, local_addr_max: 3
[  204.867189] msk->pm.subflows: 1, subflows_max: 5
[  204.882419] MPTCP: local_addr_used 1: saddr 192.168.11.250: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  204.893542] MPTCP: local_addr_used 1: saddr 100.115.77.25: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  204.904572] MPTCP: local_addr_used 1: saddr 41.147.196.145: select_local_address() successful
[  204.913094] MPTCP: saddr 41.147.196.145: __mptcp_subflow_connect() ran
[  204.919642] IPv4: running inet_addr_valid_or_nonlocal()
[  204.924874] IPv4: addr_type == RTN_UNICAST
[  204.928959] IPv4: saddr 41.147.196.145: inet_addr_valid_or_nonlocal() returned zero, __inet_bind() failed
[  204.938514] MPTCP: saddr 41.147.196.145: kernel_bind() failed with code -99
[  204.945486] MPTCP: local_addr_used 2: saddr 192.168.11.250: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  204.956605] MPTCP: local_addr_used 2: saddr 100.115.77.25: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  204.967633] MPTCP: local_addr_used 2: saddr 41.147.196.145: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  204.978748] MPTCP: select_local_address() failed
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/20)
# nmcli c modify telkom ipv4.dad-timeout 0
# nmcli c up telkom
[  215.062886] 8021q: adding VLAN 0 to HW filter on device wwu1u3i4
[  215.075248] MPTCP: check if should create a new subflow
[  215.075248] msk->pm.local_addr_used: 1, local_addr_max: 3
[  215.075248] msk->pm.subflows: 1, subflows_max: 5
[  215.090478] MPTCP: local_addr_used 1: saddr 192.168.11.250: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  215.101608] MPTCP: local_addr_used 1: saddr 100.115.77.25: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  215.112638] MPTCP: local_addr_used 1: saddr 41.147.196.145: select_local_address() successful
[  215.121159] MPTCP: saddr 41.147.196.145: __mptcp_subflow_connect() ran
[  215.127706] IPv4: running inet_addr_valid_or_nonlocal()
[  215.132947] IPv4: addr_type == RTN_LOCAL
[  215.136859] IPv4: saddr 41.147.196.145: inet_addr_valid_or_nonlocal() returned non-zero, __inet_bind() succesful
[  215.147090] MPTCP: local_addr_used 2: saddr 192.168.11.250: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  215.158212] MPTCP: local_addr_used 2: saddr 100.115.77.25: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  215.169241] MPTCP: local_addr_used 2: saddr 41.147.196.145: test_bit(entry->addr.id, msk->pm.id_avail_bitmap) returned zero
[  215.180356] MPTCP: select_local_address() failed
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/21)
# [  SF_ESTABLISHED] token=c647e4d4 remid=0 locid=9 saddr4=41.147.196.145 daddr4=102.132.169.219 sport=39729 dport=1194 backup=0 ifindex=9
```

**Comment by pabeni** [comment] 2024-07-22 13:33
> @pabeni Yup, that does indeed mitigate the issue. Should I close this issue as it has nothing to do with the kernel?

Yes, let's close this, so we can more effectively handle out backlog.

**Closed as completed by pabeni** 2024-07-22 13:33 UTC
Labels: question

**Comment by matttbe** [comment] 2025-02-24 13:27
FYI, the NM issue has recently been fixed: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/1583
