### ISSUE TITLE
Packet scheduler , Path Manager and Congestion Control

### ISSUE THREAD

**Issue by nishisahu** [multipath-tcp/mptcp_net-next#418] opened 2023-07-05 04:36 UTC
what are the current Packet Scheduler , Path Manager and Congestion Control available in MPTCP in the latest  linux kernel version . If possible can you give  changes in MPTCP in linux kernel  version 5.19 and the linux kernel version 6.2 or latest 6.4.1.
 As I am working under MPTCP project  so I need this information.

**Comment by matttbe** [comment] 2023-07-05 17:32
Hi Nishi,

You can find most answers in our [wiki](https://github.com/multipath-tcp/mptcp_net-next/wiki). 

In short:
- path manager:
  - in-kernel (default)
  - userspace (enabled via `sysctl -w net.mptcp.pm_type=1`)
- packet scheduler:
  - in-kernel (default)
  - nothing else for the moment, it is in development
- congestion control:
  - no coupled congestion control in the upstream kernel, the ones from TCP are used per subflow.
- the changelog is in our [wiki](https://github.com/multipath-tcp/mptcp_net-next/wiki#changelog)
- we recommend to always use the last stable version (or at least the last LTS one)

I guess I can close this ticket but feel free to re-open it if needed.

**Closed as completed by matttbe** 2023-07-05 17:32 UTC
Labels: question

**Comment by abhinaba-fbr** [comment] 2023-07-12 19:43
Hello @matttbe, I see, several commits for mptcp bpf schedulers (bpf_rr, bpf_red, bpf_first). Are those schedulers have been completly developed? If so, how can we configure to use them in the development-repo kernel built?

**Comment by matttbe** [comment] 2023-07-13 12:17
> Are those schedulers have been completly developed?

In short: no. These are just some "toys" to help developing the infrastructure. They don't support all cases and more work is still needed, see #350.

> If so, how can we configure to use them in the development-repo kernel built?

If you want to contribute to the MPTCP BPF packet schedulers, you will need to compile the kernel yourself and then compile the BPF selftests (`cd tools/testing/selftests/bpf && make`).

More explanations are available there: https://github.com/multipath-tcp/mptcp_net-next/issues/336#issuecomment-1499873634 (see the replies below)

**Comment by GLtangzero** [comment] 2025-05-17 08:16
@matttbe 
Hello, I would like to ask if it is feasible to develop a scheduler for MPTCP that is not based on the hot-pluggable BPF but is similar to the module-based form of MPTCPv0.

**Comment by matttbe** [comment] 2025-05-19 08:51
> Hello, I would like to ask if it is feasible to develop a scheduler for MPTCP that is not based on the hot-pluggable BPF but is similar to the module-based form of MPTCPv0.

@GLtangzero Technically, yes, but I don't think that's the direction we want to take. Why would you prefer that over a hot-pluggable BPF program written in safe C?

**Comment by GLtangzero** [comment] 2025-05-19 08:55
@matttbe
First, thanks for the reply. Because the message which I get from now, the BFP program is still in programming in the export, I'm not sure it will work or not, but still compile total kernel in MPTCPv1 is also not a good idea, as I know the mptcpv1 schedule is not a moudle but straight compile in the linux kernel.

**Comment by matttbe** [comment] 2025-05-19 09:02
> Because the message which I get from now, the BFP program is still in programming in the export, I'm not sure it will work or not

The BPF infra is there, the problem is the scheduler API, something that a kernel module would suffer from too.

So the solution is either to wait while someone improves the situation.

> but still compile total kernel in MPTCPv1 is also not a good idea, as I know the mptcpv1 schedule is not a moudle but straight compile in the linux kernel.

The constraints are different. The deprecated out-of-tree kernel was focused on MPTCP and impacting other protocols. We cannot do that with the upstream kernel.

Note: MPTCPv0 and v1 is about the protocol, not the implementation: see the [FAQ](https://www.mptcp.dev/faq.html#mptcpv0-vs-mptcpv1)

**Comment by GLtangzero** [comment] 2025-05-19 09:10
@matttbe 
Thank you very much, I will try to make progess in v0 and after v1 is stable I think it could be migration the code,
and also thank for your help and hark work, hope we can see the stable version very soon!!
