### ISSUE TITLE
BPF selftest got "fallback to TCP" error

### ISSUE THREAD

**Issue by geliangtang** [multipath-tcp/mptcp_net-next#176] opened 2021-03-30 13:00 UTC
When I ran the bpf mptcp test "./test_progs -n 67", I got a "fallback to TCP" error and a "Attempt to release TCP socket in state 8" error in the kernel log:

```
[ 2904.821675] MPTCP: subflow=000000006672aad2
[ 2904.821680] MPTCP: subflow=000000006672aad2, family=2
[ 2904.821682] MPTCP: subflow=000000006672aad2
[ 2904.821719] MPTCP: msk=00000000eaccf64d
[ 2904.821724] MPTCP: msk=00000000eaccf64d
[ 2904.821735] MPTCP: msk=00000000eaccf64d
[ 2904.822786] MPTCP: subflow=000000000003ba05
[ 2904.822789] MPTCP: subflow=000000000003ba05, family=2
[ 2904.822792] MPTCP: subflow=000000000003ba05
[ 2904.822827] MPTCP: msk=000000005818109c
[ 2904.822831] MPTCP: msk=000000005818109c
[ 2904.822868] MPTCP: ssk=00000000729b0de5, local_key=0, token=0, idsn=0
[ 2904.822924] MPTCP: subflow=000000006672aad2
[ 2904.822942] MPTCP: subflow_req=0000000025739d62, listener=000000006672aad2
[ 2904.822944] MPTCP: MP_CAPABLE version=1, flags=1, optlen=4 sndr=18446744072231269184, rcvr=18446744072228608064 len=65535
[ 2904.822949] MPTCP: req=0000000025739d62 local_key=15607636458978417890, token=3995930330, idsn=4151446240254394327
[ 2904.822961] MPTCP: subflow_req=0000000025739d62, local_key=15607636458978417890
[ 2904.822984] MPTCP: subflow=000000000003ba05 synack seq=da2e10fa
[ 2904.822986] MPTCP: MP_CAPABLE version=1, flags=1, optlen=12 sndr=15607636458978417890, rcvr=0 len=1
[ 2904.822989] MPTCP: subflow=000000000003ba05, remote_key=15607636458978417890
[ 2904.822990] MPTCP: msk=000000005818109c, token=3138387826
[ 2904.822993] MPTCP: msk=000000005818109c, token=3138387826 side=0
[ 2904.822997] MPTCP: msk=000000005818109c ssk=00000000729b0de5 data_avail=0 skb=0000000000000000
[ 2904.823000] MPTCP: msk=000000005818109c ssk=00000000729b0de5 status=2
[ 2904.823007] MPTCP: subflow=000000000003ba05, local_key=13360476977887136047, remote_key=15607636458978417890 map_len=0
[ 2904.823018] MPTCP: listener=000000006672aad2, req=0000000025739d62, conn=00000000eaccf64d
[ 2904.823020] MPTCP: MP_CAPABLE version=1, flags=1, optlen=20 sndr=13360476977887136047, rcvr=15607636458978417890 len=65535
[ 2904.823055] MPTCP: subflow=000000002491d623
[ 2904.823064] MPTCP: msk=00000000a0271c19, token=3995930330 side=1
[ 2904.823080] MPTCP: msk=00000000a0271c19 ssk=000000008dd7431f data_avail=0 skb=0000000000000000
[ 2904.823082] MPTCP: msk=00000000a0271c19 ssk=000000008dd7431f status=2
[ 2904.823084] MPTCP: MP_CAPABLE version=1, flags=1, optlen=20 sndr=13360476977887136047, rcvr=15607636458978417890 len=38754
[ 2904.823104] MPTCP: msk=000000005818109c snd_data_fin_enable=0 shutdown=3 state=4 pending=0
[ 2904.823107] MPTCP: msk=000000005818109c snd_data_fin_enable=1 pending=0 snd_nxt=5209280520537872386 write_seq=5209280520537872387
[ 2904.823110] MPTCP: Sending DATA_FIN on subflow 00000000729b0de5
[ 2904.823128] MPTCP: DSS
[ 2904.823131] MPTCP: data_fin=1 dsn64=1 use_map=1 ack64=0 use_ack=1
[ 2904.823133] MPTCP: data_ack=914259928
[ 2904.823134] MPTCP: data_seq=5209280520537872386 subflow_seq=0 data_len=1
[ 2904.823150] MPTCP: msk=000000005818109c state=4
[ 2904.823212] MPTCP: msk=00000000eaccf64d state=7
[ 2904.823214] MPTCP: msk=00000000eaccf64d
[ 2904.823240] MPTCP: subflow_req=0000000025739d62
[ 2904.823250] MPTCP: check_fully_established:fallback to TCP (msk=000000005818109c)
[ 2904.823306] MPTCP: msk=00000000eaccf64d
[ 2904.823526] MPTCP: msk=00000000a0271c19 snd_data_fin_enable=0 pending=0 snd_nxt=4151446240254394328 write_seq=4151446240254394328
[ 2904.823533] MPTCP: msk=00000000a0271c19
[ 2904.823535] IPv4: Attempt to release TCP socket in state 8 00000000a0271c19
[ 2954.415879] MPTCP: msk=00000000474e8657 snd_data_fin_enable=1 pending=0 snd_nxt=14603538848639169953 write_seq=14603538848639169953
[ 2954.415911] MPTCP: msk=00000000474e8657
[ 2954.416151] MPTCP: msk=00000000474e8657
[ 2966.704256] MPTCP: msk=000000005818109c snd_data_fin_enable=1 pending=0 snd_nxt=5209280520537872387 write_seq=5209280520537872387
[ 2966.704279] MPTCP: msk=000000005818109c
```

**Comment by matttbe** [comment] 2021-03-30 13:56
See initial discussions on the ML:
- v1: https://patchwork.ozlabs.org/project/mptcp/patch/70cec4a8462feb0ad4771dd1a0d75f3163800059.1615983074.git.geliangtang@gmail.com/
- v2: https://patchwork.ozlabs.org/project/mptcp/patch/9fe955db44222c638db73c3f8446d9d248b8a11c.1616039100.git.geliangtang@gmail.com/

**Comment by darkwrat** [comment] 2021-04-26 06:55
I've noticed `Attempt to release TCP socket in state 8` errors appear when a process exits, that had unaccepted connections in backlog. Here is a simple reproducer.

```
#include <netinet/in.h>

int main(void)
{
	struct sockaddr_in sa;
	sa.sin_family = AF_INET;
	sa.sin_port = htons(12345);
	sa.sin_addr.s_addr = htonl(INADDR_LOOPBACK);

	int lfd = socket(AF_INET, SOCK_STREAM, IPPROTO_MPTCP);
	bind(lfd, (struct sockaddr *)&sa, sizeof(sa));
	listen(lfd, 100);

	for (int i = 0; i < 10; i++) {
		int sock = socket(AF_INET, SOCK_STREAM, IPPROTO_MPTCP);
		connect(sock, (struct sockaddr *)&sa, sizeof(sa));
	}
}
```

**Comment by matttbe** [comment] 2021-04-26 07:06
@darkwrat Thank you for looking at that.

So in your case, there is no BPF program loaded, right? And I guess you don't have the same issue with `IPPROTO_TCP`, right?
I guess we don't manage this case properly.

**Comment by darkwrat** [comment] 2021-04-26 07:18
> @darkwrat Thank you for looking at that.
> 
> So in your case, there is no BPF program loaded, right? And I guess you don't have the same issue with `IPPROTO_TCP`, right?
> I guess we don't manage this case properly.

I have not loaded any BPF programs. And I have tried changing protocol to IPPROTO_TCP for both client and server sockets, one at a time. `Attempt to release TCP socket in state 8` is only observable when both of them are IPPROTO_MPTCP,  on 5.11.13-200.fc33.x86_64 and also on mptcp_net-next kernel from 0ef01ab.

**Comment by matttbe** [comment] 2021-04-26 07:35
@darkwrat Thank you for this, very useful. I'm going to create a new bug report to split the two issues.

**Comment by matttbe** [comment] 2021-04-26 08:48
Let's focus here only on the "fallback to TCP" error. For the other one, please look at #185

**Comment by geliangtang** [comment] 2021-05-07 06:38
@matttbe @darkwrat

drakwrat's test can reproduce the "fallback to TCP" error too:

```
#include <netinet/in.h>

int main(void)
{
	struct sockaddr_in sa;
	sa.sin_family = AF_INET;
	sa.sin_port = htons(12345);
	sa.sin_addr.s_addr = htonl(INADDR_LOOPBACK);

	int lfd = socket(AF_INET, SOCK_STREAM, IPPROTO_MPTCP);
	bind(lfd, (struct sockaddr *)&sa, sizeof(sa));
	listen(lfd, 100);

	int sock = socket(AF_INET, SOCK_STREAM, IPPROTO_MPTCP);
	connect(sock, (struct sockaddr *)&sa, sizeof(sa));

	return 0;
}
```
----

<7>[ 1477.059635] MPTCP: msk=000000006bf0cf61
<7>[ 1485.132216] MPTCP: subflow=000000002296fc22
<7>[ 1485.132233] MPTCP: subflow=000000002296fc22, family=2
<7>[ 1485.132242] MPTCP: subflow=000000002296fc22
<7>[ 1485.132411] MPTCP: msk=000000005b84960a
<7>[ 1485.132688] MPTCP: subflow=000000002388ad62
<7>[ 1485.132695] MPTCP: subflow=000000002388ad62, family=2
<7>[ 1485.132702] MPTCP: subflow=000000002388ad62
<7>[ 1485.132974] MPTCP: ssk=000000005ab5dbc8, local_key=9186175039591172243, token=2833190200, idsn=13562085501921405456
<7>[ 1485.133131] MPTCP: subflow=000000002296fc22
<7>[ 1485.133200] MPTCP: subflow_req=00000000ca26b42c, listener=000000002296fc22
<7>[ 1485.133209] MPTCP: MP_CAPABLE version=1, flags=1, optlen=4 sndr=582, rcvr=18446744072046692096 len=65535 csum=65535
<7>[ 1485.133227] MPTCP: req=00000000ca26b42c local_key=9900409276882973726, token=2796355457, idsn=5747750831347864753
<7>[ 1485.133288] MPTCP: subflow_req=00000000ca26b42c, local_key=9900409276882973726
<7>[ 1485.133384] MPTCP: subflow=000000002388ad62 synack seq=72748901
<7>[ 1485.133393] MPTCP: MP_CAPABLE version=1, flags=1, optlen=12 sndr=9900409276882973726, rcvr=18446633460193955073 len=0 csum=0
<7>[ 1485.133402] MPTCP: subflow=000000002388ad62, remote_key=9900409276882973726
<7>[ 1485.133409] MPTCP: msk=00000000875940e7, token=2833190200
<7>[ 1485.133416] MPTCP: msk=00000000875940e7, token=2833190200 side=0
<7>[ 1485.133457] MPTCP: subflow=000000002388ad62, local_key=9186175039591172243, remote_key=9900409276882973726 map_len=0
<7>[ 1485.133490] MPTCP: listener=000000002296fc22, req=00000000ca26b42c, conn=000000005b84960a
<7>[ 1485.133499] MPTCP: MP_CAPABLE version=1, flags=1, optlen=20 sndr=9186175039591172243, rcvr=9900409276882973726 len=0 csum=0
<7>[ 1485.133587] MPTCP: subflow=000000000587a2a5
<7>[ 1485.133625] MPTCP: msk=000000005dcb6e30, token=2796355457 side=1
<7>[ 1485.133658] MPTCP: MP_CAPABLE version=1, flags=1, optlen=20 sndr=9186175039591172243, rcvr=9900409276882973726 len=39782 csum=65535
<7>[ 1485.134972] MPTCP: msk=00000000875940e7 snd_data_fin_enable=0 shutdown=3 state=4 pending=0
<7>[ 1485.134987] MPTCP: msk=00000000875940e7 snd_data_fin_enable=1 pending=0 snd_nxt=13562085501921405457 write_seq=13562085501921405458
<7>[ 1485.134998] MPTCP: Sending DATA_FIN on subflow 000000005ab5dbc8
<7>[ 1485.135083] MPTCP: DSS
<7>[ 1485.135089] MPTCP: data_fin=1 dsn64=1 use_map=1 ack64=0 use_ack=1
<7>[ 1485.135097] MPTCP: data_ack=2683442354
<7>[ 1485.135102] MPTCP: data_seq=13562085501921405457 subflow_seq=0 data_len=1 csum=0:0
<7>[ 1485.135198] MPTCP: msk=000000005dcb6e30 snd_data_fin_enable=0 pending=0 snd_nxt=5747750831347864754 write_seq=5747750831347864754
<7>[ 1485.135233] MPTCP: msk=00000000875940e7 state=4
<7>[ 1485.135297] MPTCP: msk=000000005b84960a state=7
<7>[ 1485.135302] MPTCP: msk=000000005b84960a
<7>[ 1485.135387] MPTCP: msk=000000005dcb6e30
<7>[ 1485.135436] MPTCP: subflow_req=00000000ca26b42c
<7>[ 1485.135472] MPTCP: check_fully_established:fallback to TCP (msk=00000000875940e7)
<7>[ 1485.135628] MPTCP: msk=000000005b84960a
<7>[ 1485.339305] MPTCP: msk=00000000875940e7 snd_data_fin_enable=1 pending=0 snd_nxt=13562085501921405458 write_seq=13562085501921405458
<7>[ 1485.339329] MPTCP: msk=00000000875940e7

----

**Comment by matttbe** [comment] 2021-05-07 07:54
@geliangtang I just realised that but is it really an error?

I think we are in a situation where we expect the [`MP_CAPABLE`'s 4th ACK](https://www.rfc-editor.org/rfc/rfc8684.html#section-3.1-6.4) but instead, we get a FIN (I guess, see `[ 1485.135233] MPTCP: msk=00000000875940e7 state=4`). Because the MPTCP connection was not fully established, we don't need to send a DATA_FIN, we can fallback to TCP and send a FIN as well.

I don't see anything in the RFC how to react in this specific case but maybe I missed it: 
 https://www.rfc-editor.org/rfc/rfc8684.html#section-3.1-15
But I think we react well.

Maybe we could check if we got a FIN before printing the fallback message but at the end, that's a debug message and a previous debug msg already indicates that we were in `FIN_WAIT1`.

WDYT? Should we close this ticket? Or do you think about something simple to avoid any confusion?

**Comment by geliangtang** [comment] 2021-05-07 08:05
@matttbe I just sent a patch to the ML to avoid fallback to TCP when data_fin enabled.

**Closed as completed** 2021-05-24 07:17 UTC
Labels: bug
