### ISSUE TITLE
If MPTCP primary flow is over tun interface, no subflow gets created

### ISSUE THREAD

**Issue by Monika-Research** [multipath-tcp/mptcp_net-next#395] opened 2023-04-25 10:30 UTC
Hi Team,

I have a tun interface created using tunslip6. It operates over low power wireless network and is capable of achieving a few Kbps. For an instance, when iperf is run between two such tun interfaces each hosted on a ubuntu system, I get around 150 Kbps.
Server:  iperf3 -s 
Client: iperf3 -c fd01::1 -l100 -b150K

When I try to use MPTCP over WiFi and tun interface, 
(i) if WiFi is the primary flow, I see traffic transmitted only over WiFi interface and nothing over the subflow tun interface.
(ii) if tun is the primary flow, I don't even see subflow getting established over WiFi (no join request is being sent)

Can anyone please advise on this?
Thanks,
Monika

**Comment by matttbe** [comment] 2023-04-25 11:56
Hi Monika,

> I have a tun interface created using tunslip6. It operates over low power wireless network and is capable of achieving a few Kbps. 

What's the approximative latency on this link?

>  (i) if WiFi is the primary flow, I see traffic transmitted only over WiFi interface and nothing over the subflow tun interface.

What do you mean when saying "nothing"? Not even the establishment of the second subflow?

If the latency over the tun network is bad, the expected behaviour is not to use it: if using the link delay all the connexion without being able to increase the bandwidth because you might be limited by buffer or introduce some bufferbloat, it is better not to use this link.

>  (ii) if tun is the primary flow, I don't even see subflow getting established over WiFi (no join request is being sent)

It sounds like there is an issue with your network configuration: probably the `ip mptcp endpoint` (or `limit`) on both the client and server? Or the [routing rules](https://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting)?

What's the kernel version your are using?

**Comment by Monika-Research** [comment] 2023-04-26 07:03
Hi Matt, 

**What's the approximative latency on this link?**
The average ping latency on this link is around 12ms.

**What do you mean when saying "nothing"? Not even the establishment of the second subflow?**
Subflow does get established. But not utilized as you said - latency of this link too huge when compared to WiFi link.

**It sounds like there is an issue with your network configuration: probably the ip mptcp endpoint (or limit) on both the client and server? Or the [routing rules](https://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting)?**
The routing rules should be fine as I see subflow getting established if I set the primary flow as WiFi. Only when I set the tun interface as primary flow, I don't get to see even subflow getting established. No join request seen.

I see the performance degrading from 150Kbps to 100Kbps when I try to use MPTCP(single link) instead of TCP with this low power wireless link. So, there is a possibility that the low power wireless protocol itself has some issues when it works with TCP and it is getting worse when I use it with MPTCP (retransmissions increasing).

**Comment by matttbe** [comment] 2023-04-26 07:51
> The routing rules should be fine as I see subflow getting established if I set the primary flow as WiFi.

Maybe it is not fine for the "tun" one. You can easily check by looking at the output of this command and see if the correct interface is reported:

```
ip route get from <IP tun interface>
```

Also check the `endpoints` and `limits` as mentioned above.

> I see the performance degrading from 150Kbps to 100Kbps when I try to use MPTCP(single link) instead of TCP with this low power wireless link. So, there is a possibility that the low power wireless protocol itself has some issues when it works with TCP and it is getting worse when I use it with MPTCP (retransmissions increasing).

Interesting, it should not be the case with just one subflow. Which kernel version are you using?

**Comment by Monika-Research** [comment] 2023-04-26 12:14
**Maybe it is not fine for the "tun" one. You can easily check by looking at the output of this command and see if the correct interface is reported:**

At the client:
ip route get from fc02::1 fc01::1
fc01::1 from fc02::1 via fc02::f6ce:3638:5c8a:5b14 dev tun0 table 1 src fc02::1 metric 1024 pref medium

**Also check the endpoints and limits as mentioned above.**
At the client:
ip mptcp limits - add_addr_accepted 1 subflows 1
At the server:
ip mptcp limits - add_addr_accepted 0 subflows 1
ip mptcp endpoint - 2001:db8:0:f102::1 id 1 signal

nstat MPTcp* - only shows MPTCPExtMPCapablesSYNTX and MPTCPExtMPCapablesSYNACKRX. Join is not seen.

However if WiFi is used as the primary flow,
At the server:
ip mptcp endpoint - fc01::1 id 1 signal
subflow gets established over tun interface. I see MPTCPExtMPJoinSYN stuff in nstat MPTcp* as well as SF_ANNOUNCED and SF_ESTABLISHED with ip mptcp monitor.

It is only when tun is used as primary flow, I don't see subflow getting established over the other link (WiFi).

**Which kernel version are you using?**
uname -a -> Linux ubuntu 6.1.2-v8+

**Comment by Monika-Research** [comment] 2023-04-28 06:12
Hi Matt,
Hope you are doing well.

Any leads on this? 

I tried with 2 WiFi links as well. Subflow gets established over the WiFi link (the same link that I tried with tun ). Same ip mptcp endpoint configuration works when the WiFi (subflow) link is used with another WiFi link. However not with tun. (I am trying to say that endpoint configuration is correct)

I tried to compare the pcaps of (i) MPTCP over two WiFi links and (ii) MPTCP over WiFi and tun (low power wireless) and observed the following
In the SYN packet (MPTCP Capable), under MPTCP Analysis, TCP subflow stream id(s): 1 0 for (i)
                                                                                                    TCP subflow stream id(s): 0 for (ii)

When can MPTCP subflow announcement could fail to occur? I mean, what are the possible situations that it is bound to happen?

Thanks,
Monika

**Comment by Monika-Research** [comment] 2023-05-01 11:27
Hi,

I would like to know if there are any timers for subflow establishment. I am wondering if any such exists, as the primary flow's (over tun interface) latency is huge, the time taken for connection establishment is expected to be too big. Is it affecting the consequent subflow establishment ? I am purely guessing.

None of the logs (ss, ip mptcp monitor, pcaps) have helped so far :(

**Comment by matttbe** [comment] 2023-06-02 15:08
Sorry for the delay. I was off and missed the notifications.

Could it be possible that you are limited by the `ip mptcp limit (...) 1`? I  don't know your exact configuration but maybe it first tries to use IPs that cannot work and it is limited by that. Maybe just try to increase the limits.

Also, be careful not to have `mptcpd` configuring other endpoints. (`ip mptcp endpoints`)

**Comment by matttbe** [comment] 2023-07-12 08:21
I suggest to close this old ticket. Feel free to re-open it and provide answers to my previous questions if you still have the issue.

**Closed as completed by matttbe** 2023-07-12 08:21 UTC
Labels: question
