### ISSUE TITLE
fail to create a subflow when a listen socket is closed

### ISSUE THREAD

**Issue by nsdyoshi** [multipath-tcp/mptcp_net-next#293] opened 2022-08-17 09:05 UTC
Hello,
I wrote a bit tricky code that closes a listen socket after it accepts an MPTCP connection. 
Then, I've noticed that we cannot establish subflows when a listen socket is closed. 
But, I am wondering if this is a correct behavior.

Because the mptcp connection is already established, I think the listen socket should not affect subflow creations.
Is this  intended?

**Comment by matttbe** [comment] 2022-08-17 10:52
Hi @nsdyoshi 

This is the expected behaviour.

There were quite a bit of discussions about that and even patches to change this behaviour, see: https://github.com/multipath-tcp/mptcp_net-next/issues/203#issuecomment-1071095112

But due to technical issues, we prefer to let the userspace managing this, see https://github.com/intel/mptcpd/issues/223 .

Would it be OK if your application does something like `listen(sock, 0)` after the `close()`? (or limit the backlog to 1 instead of closing the socket)

**Comment by nsdyoshi** [comment] 2022-08-18 08:40
Hi @matttbe Thank you so much for your quick response.

I've tried with listen(sock, 0) after close(), but it didn't work.
But, this is not what we want anyway. 

I've checked https://github.com/intel/mptcpd/issues/223 . I am guessing that we might be able to have a work around if we use userspace path manager. If so, I will try it.

**Comment by matttbe** [comment] 2022-08-18 08:54
> I've tried with listen(sock, 0) after close(), but it didn't work.

I wonder if it is not due to issue #290.
But if your `fd` has been `close()`, I thought it would not be an issue to re-create the `socket()`, `bind()` and `listen()` without being affected by #290.

> I've checked [intel/mptcpd#223](https://github.com/intel/mptcpd/issues/223) . I am guessing that we might be able to have a work around if we use userspace path manager. If so, I will try it.

[intel/mptcpd#223](https://github.com/intel/mptcpd/issues/223) issue has not been implemented yet but it is planned (I don't have the details about that).

**EDIT**: an early implementation seems available apparently but I don't know how to enable it.

**Comment by nsdyoshi** [comment] 2022-08-19 08:48
I think I was not clear enough, Sorry... When we close socket, we can re-create socket, then do bind and listen,etc. 
A problem is if MPTCP join arrives before the socket is re-created, the subflow creation will be failed. This is a bit problematic in race conditions.

I will investigate the userland path manager to see if there's any work around. Thanks for the info

**Comment by matttbe** [comment] 2022-08-19 09:12
> A problem is if MPTCP join arrives before the socket is re-created, the subflow creation will be failed. This is a bit problematic in race conditions.

I understand. Do you want to establish a new subflows to the server IP used by the initial subflow?
`mptcpd` will do a socket+bind+listen on the additional IP that is going to be announced by the server. It works well if your server has for example 2 IPs, the connection has been established on the "primary" IP and the goal is to have new subflows established on the "second" IP.
In this case, your app can close the listening socket after the `accept()` and `mptcpd` can then create a new socket, `bind` on the 2nd IP, do a listen with 0 for the backlog and then only announce the second IP. Please note that your app can then also create this socket and bind on the second IP prior creating the  "main" socket if you see what I mean.

Would that work for you?

**Comment by nsdyoshi** [comment] 2022-08-23 18:27
Thanks for the comment. This looks like a good idea for us. We will explore it a bit more.
Thank you so much for the advice.

**Comment by matttbe** [comment] 2022-08-29 14:58
If you can use the latest mptcpd version (0.11), Ossama shared more details about the control you can have on the new "listener manager": https://github.com/intel/mptcpd/issues/223#issuecomment-1219670331

**Comment by matttbe** [comment] 2022-09-01 13:29
Please note that what is currently not well supported is if you want new subflows to be established on the initial destination IP after having closed the listening socket. To support new subflows, you would have to close the socket and re-open a new one with a listening backlog set to 0. It is not well supported because  the new subflow request might arrive between the `close()` and the `listen(fd, 0)` as you mentioned.

But then the question is: why not creating the listening socket with a `backlog` set to a certain size (e.g. 1)? Would it not be possible for your use case?

An alternative could be to implement a dedicated MPTCP socket option either to change the backlog size (if that is currently not possible, to be checked) or defer the actual close (not allowing new MPTCP connections but accepting subflows).

**Comment by matttbe** [comment] 2022-09-16 16:35
Hi @nsdyoshi 

By chance, did you have the opportunity to explore the different solutions?
Do you think we can close this ticket?

**Comment by nsdyoshi** [comment] 2022-09-18 23:44
Hi @matttbe 
Yes, Please close this ticket as I've confirmed that a solution by using 2 IPs works for me.
If the listening socket is bound to only one IP and add the other IP as a new endpoint, I was able to create subflows even if the listening socket is closed.

**Closed as completed** 2022-09-19 11:39 UTC
Labels: question
