### ISSUE TITLE
[syzbot] WARNING in `__mptcp_move_skbs_from_subflow`

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#513] opened 2024-08-07 04:45 UTC
Raising awareness here to this issue: https://syzkaller.appspot.com/bug?id=e1909b42f954d6302231753e99ff2fef6d763447

We are hitting this as well in our deployment.

**Comment by matttbe** [comment] 2024-08-07 15:51
@cpaasch : thank you for this reminder. By chance, do you have a reproducer? Did you get it while validating the `export` branch?

**Comment by cpaasch** [comment] 2024-08-08 15:48
No reproducer yet.

**Comment by pabeni** [comment] 2024-08-21 15:13
Some occurrence of the reported splats should be fixed by the following commit

commit 68cc924729ffcfe90d0383177192030a9aeb2ee4
Author: Paolo Abeni <pabeni@redhat.com>
Date:   Wed Jul 31 12:10:15 2024 +0200

    mptcp: fix duplicate data handling

According to the syzbot status, syzkaller was able to reproduce the splat on top of linux@6a0e38264012 which includes the above commit, so there should be something more.

**Comment by pabeni** [comment] 2024-08-21 15:22
The splat is caused by a somewhat bad mapping: the current data mapping covers only partially the current skb contents. In theory we could 'downgrade' the warning to a dbg message and/or a mib count increase, as an evil/bad pear could trigger this at will, but syzkaller is observing the splat when the peer is the in-tree mptcp implementation: we need to dig the root cause.

**Comment by cpaasch** [comment] 2024-08-21 15:54
> The splat is caused by a somewhat bad mapping: the current data mapping covers only partially the current skb contents

Yes, that is something that can happen, so downgrading to dbg with a MIB-counter would be good.

**Closed as completed** 2024-09-30 17:47 UTC
Labels: bug, syzkaller
