### ISSUE TITLE
syzkaller: memory leak in `subflow_ulp_init`

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#398] opened 2023-05-04 19:26 UTC
syzkaller-Id: 0d9f6b2c2f5a4a7863807076070249b187d1d271

HEAD: 74a1b717b26e5 (6/7)
7639ac56dfbc (6/2)
ffcc7899081b (5/25)
770d503b8315

Trace:
```
sendmsg$IPCTNL_MSG_TIMEOUT_NEW(r2, &(0x7f00000002c0)={0x0, 0x0, &(0x7f0000000280)={&(0x7f0000000240)={0x14, 0x0, 0x8, 0x101}, 0x14}}, 0x20000010)
BUG: memory leak
unreferenced object 0xffff88812a161200 (size 256):
  comm "syz-executor.5", pid 11910, jiffies 4295874473 (age 67.531s)
  hex dump (first 32 bytes):
    00 01 00 00 00 00 ad de 22 01 00 00 00 00 ad de  ........".......
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  backtrace:
    [<000000006aeff35f>] __kmem_cache_alloc_node+0xf6/0x1e0 mm/slub.c:3452
    [<0000000087654f15>] kmalloc_trace+0x2a/0xa0 mm/slab_common.c:1057
    [<00000000af89ab7f>] kmalloc include/linux/slab.h:560 [inline]
    [<00000000af89ab7f>] kzalloc include/linux/slab.h:681 [inline]
    [<00000000af89ab7f>] subflow_create_ctx net/mptcp/subflow.c:1749 [inline]
    [<00000000af89ab7f>] subflow_ulp_init+0x4e/0x170 net/mptcp/subflow.c:1900
    [<000000003bd4f214>] tcp_set_ulp+0x181/0x1c0 net/ipv4/tcp_ulp.c:146
    [<000000009198eb1d>] mptcp_subflow_create_socket+0x228/0x440 net/mptcp/subflow.c:1712
    [<0000000039ce421e>] __mptcp_nmpc_socket+0x9b/0x200 net/mptcp/protocol.c:89
    [<00000000ecfa869b>] mptcp_sendmsg_fastopen+0x4b/0x1c0 net/mptcp/protocol.c:1726
    [<0000000000be8ab3>] mptcp_sendmsg+0x766/0x830 net/mptcp/protocol.c:1778
    [<00000000902cea61>] ____sys_sendmsg+0x383/0x3d0 net/socket.c:724
    [<00000000f3753bba>] ___sys_sendmsg+0x143/0x190 net/socket.c:2557
    [<000000006026dcf1>] __sys_sendmmsg+0x185/0x340 net/socket.c:2643
    [<00000000969b82cc>] __do_sys_sendmmsg net/socket.c:2672 [inline]
    [<00000000969b82cc>] __se_sys_sendmmsg net/socket.c:2669 [inline]
    [<00000000969b82cc>] __x64_sys_sendmmsg+0x25/0x30 net/socket.c:2669
    [<00000000f91ccd7e>] do_syscall_x64 arch/x86/entry/common.c:50 [inline]
    [<00000000f91ccd7e>] do_syscall_64+0x45/0xa0 arch/x86/entry/common.c:80
    [<00000000ddf63ef3>] entry_SYSCALL_64_after_hwframe+0x72/0xdc

BUG: leak checking failed
```

No reproducer yet.
[Kconfig_k8_kmemleak.txt](https://github.com/multipath-tcp/mptcp_net-next/files/11400846/Kconfig_k8_kmemleak.txt)

Kconfig:

**Comment by matttbe** [comment] 2023-05-05 05:45
Maybe a `sendmsg(MSG_FASTOPEN)` on a non first subflow?

**Comment by pabeni** [comment] 2023-05-15 10:20
@cpaasch: can you observe this issue frequently? do you have access to the syzkaller logs ~ 'age' seconds old (in this case 67.531s, restricted to syz-executor.5) -> just to have an idea about possible programs hitting the issue.

FTR, the leaked structure is the mptcp subflow context, for client/active first subflow created on fastopen. If there are no other leaked objects, it looks like the leak happens after detaching the context from the socket - likely after tcp_cleanup_ulp()/inet_csk_destroy_sock()

**Comment by cpaasch** [comment] 2023-05-16 00:17
@pabeni:

No, I only have a single instance of this.

Here are the programs that were executed around the relevant time-frame and created a MPTCP-socket.\:

```
16:47:58 executing program 6:
r0 = socket$netlink(0x10, 0x3, 0x0)
ioctl$sock_SIOCGIFINDEX(r0, 0x8933, &(0x7f0000000140)={'ip6gretap0\x00'})
r1 = socket$inet_mptcp(0x2, 0x1, 0x106)
r2 = dup(r1)
sendmmsg$inet(r2, &(0x7f0000000300)=[{{&(0x7f0000000080)={0x2, 0x4001, @remote}, 0x10, 0x0}}], 0x1, 0x2004c04f)
sendmsg$nl_netfilter(r2, &(0x7f0000000100)={&(0x7f0000000000)={0x10, 0x0, 0x0, 0x100000}, 0xc, &(0x7f00000000c0)={&(0x7f0000000040)=ANY=[@ANYBLOB="78000000110b01022cbd7000fbdbdf251f000001e96f57e012f2f587c7bec3c02d3f4e2b1cf9f1050752b347424852e9002de1eb490b46a797f8a33b0867e1b30b2761d86399a9c96ce31d5cbd135383716b4cc5637a8a77acbb872fab24cc2933bd18abb431ca067fce0f0c0bd1bce59c0db986e7b25660"], 0x78}, 0x1, 0x0, 0x0, 0x40000}, 0x4004055)
sendmsg$NL80211_CMD_NEW_KEY(r0, &(0x7f0000000780)={0x0, 0x0, &(0x7f0000000740)={0x0}, 0x1, 0x0, 0x2}, 0x0)
socket$netlink(0x10, 0x3, 0x0) (async)
ioctl$sock_SIOCGIFINDEX(r0, 0x8933, &(0x7f0000000140)={'ip6gretap0\x00'}) (async)
socket$inet_mptcp(0x2, 0x1, 0x106) (async)
dup(r1) (async)
sendmmsg$inet(r2, &(0x7f0000000300)=[{{&(0x7f0000000080)={0x2, 0x4001, @remote}, 0x10, 0x0}}], 0x1, 0x2004c04f) (async)
sendmsg$nl_netfilter(r2, &(0x7f0000000100)={&(0x7f0000000000)={0x10, 0x0, 0x0, 0x100000}, 0xc, &(0x7f00000000c0)={&(0x7f0000000040)=ANY=[@ANYBLOB="78000000110b01022cbd7000fbdbdf251f000001e96f57e012f2f587c7bec3c02d3f4e2b1cf9f1050752b347424852e9002de1eb490b46a797f8a33b0867e1b30b2761d86399a9c96ce31d5cbd135383716b4cc5637a8a77acbb872fab24cc2933bd18abb431ca067fce0f0c0bd1bce59c0db986e7b25660"], 0x78}, 0x1, 0x0, 0x0, 0x40000}, 0x4004055) (async)
sendmsg$NL80211_CMD_NEW_KEY(r0, &(0x7f0000000780)={0x0, 0x0, &(0x7f0000000740)={0x0}, 0x1, 0x0, 0x2}, 0x0) (async)

16:47:58 executing program 3:
r0 = socket$inet_dccp(0x2, 0x6, 0x0)
setsockopt$IP_VS_SO_SET_TIMEOUT(0xffffffffffffffff, 0x0, 0x48a, &(0x7f00000001c0)={0x8, 0x4, 0x4}, 0xc)
r1 = socket$nl_netfilter(0x10, 0x3, 0xc)
r2 = dup2(r1, r0)
setsockopt$SO_ATTACH_FILTER(r0, 0x1, 0x1a, &(0x7f0000000040)={0x3, &(0x7f0000000000)=[{0x2c}, {0x45}, {0x6}]}, 0x10)
sendmsg$IPCTNL_MSG_CT_GET_STATS(r2, &(0x7f0000000280)={0x0, 0x0, &(0x7f0000000240)={&(0x7f0000000200)={0x14, 0x5, 0x1, 0x101}, 0x14}}, 0x0)
r3 = socket$inet_mptcp(0x2, 0x1, 0x106)
r4 = dup(r3)
sendmmsg$inet(r4, &(0x7f0000000300)=[{{&(0x7f0000000080)={0x2, 0x4001, @remote}, 0x10, 0x0}}], 0x1, 0x2004c04f)
r5 = socket$nl_generic(0x10, 0x3, 0x10)
r6 = syz_genetlink_get_family_id$batadv(&(0x7f00000003c0), 0xffffffffffffffff)
r7 = socket$igmp6(0xa, 0x3, 0x2)
r8 = socket$packet(0x11, 0x2, 0x300)
ioctl$ifreq_SIOCGIFINDEX_batadv_mesh(r8, 0x8933, &(0x7f0000000180)={'batadv0\x00', <r9=>0x0})
ioctl$ifreq_SIOCGIFINDEX_batadv_mesh(r7, 0x8933, &(0x7f0000000100)={'batadv0\x00', <r10=>0x0})
sendmsg$BATADV_CMD_SET_MESH(r5, &(0x7f0000000480)={0x0, 0x0, &(0x7f0000000440)={&(0x7f0000000000)={0x24, r6, 0x1, 0x0, 0x0, {}, [@BATADV_ATTR_MESH_IFINDEX={0x8, 0x3, r10}, @BATADV_ATTR_DISTRIBUTED_ARP_TABLE_ENABLED={0x5, 0x2f, 0x1}]}, 0x24}}, 0x0)
sendmsg$BATADV_CMD_GET_ROUTING_ALGOS(r4, &(0x7f0000000140)={&(0x7f0000000080)={0x10, 0x0, 0x0, 0x10}, 0xc, &(0x7f0000000100)={&(0x7f00000000c0)={0x24, r6, 0x328, 0x70bd29, 0x25dfdbfd, {}, [@BATADV_ATTR_BONDING_ENABLED={0x5, 0x2d, 0x1}, @BATADV_ATTR_HARD_IFINDEX={0x8}]}, 0x24}, 0x1, 0x0, 0x0, 0x20040044}, 0x880)
r11 = syz_genetlink_get_family_id$ethtool(&(0x7f0000000340), r5)
sendmsg$ETHTOOL_MSG_STRSET_GET(0xffffffffffffffff, &(0x7f0000000400)={&(0x7f00000002c0)={0x10, 0x0, 0x0, 0x400}, 0xc, &(0x7f0000000380)={&(0x7f00000004c0)={0x1a0, r11, 0x1, 0x70bd29, 0x25dfdbfc, {}, [@ETHTOOL_A_STRSET_COUNTS_ONLY={0x4}, @ETHTOOL_A_STRSET_HEADER={0x20, 0x1, 0x0, 0x1, [@ETHTOOL_A_HEADER_FLAGS={0x8, 0x3, 0x1}, @ETHTOOL_A_HEADER_DEV_NAME={0x14, 0x2, 'veth0_vlan\x00'}]}, @ETHTOOL_A_STRSET_STRINGSETS={0x10, 0x2, 0x0, 0x1, [{0xc, 0x1, 0x0, 0x1, [@ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x6}]}]}, @ETHTOOL_A_STRSET_STRINGSETS={0x44, 0x2, 0x0, 0x1, [{0x1c, 0x1, 0x0, 0x1, [@ETHTOOL_A_STRINGSET_ID={0x8}, @ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x7}, @ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x1}]}, {0xc, 0x1, 0x0, 0x1, [@ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x1}]}, {0xc, 0x1, 0x0, 0x1, [@ETHTOOL_A_STRINGSET_ID={0x8}]}, {0xc, 0x1, 0x0, 0x1, [@ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x2}]}]}, @ETHTOOL_A_STRSET_STRINGSETS={0xac, 0x2, 0x0, 0x1, [{0x2c, 0x1, 0x0, 0x1, [@ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x1}, @ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x1}, @ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x7}, @ETHTOOL_A_STRINGSET_ID={0x8}, @ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x7}]}, {0x14, 0x1, 0x0, 0x1, [@ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x2}, @ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x7}]}, {0x1c, 0x1, 0x0, 0x1, [@ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x7}, @ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x3}, @ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x4539f0e296829a5}]}, {0x34, 0x1, 0x0, 0x1, [@ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x3}, @ETHTOOL_A_STRINGSET_ID={0x8}, @ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x8}, @ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x5}, @ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x1}, @ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x5}]}, {0xc, 0x1, 0x0, 0x1, [@ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x5}]}, {0xc, 0x1, 0x0, 0x1, [@ETHTOOL_A_STRINGSET_ID={0x8, 0x1, 0x7}]}]}, @ETHTOOL_A_STRSET_HEADER={0x30, 0x1, 0x0, 0x1, [@ETHTOOL_A_HEADER_DEV_INDEX={0x8, 0x1, r9}, @ETHTOOL_A_HEADER_DEV_INDEX={0x8, 0x1, r9}, @ETHTOOL_A_HEADER_DEV_NAME={0x14, 0x2, 'veth0_vlan\x00'}, @ETHTOOL_A_HEADER_FLAGS={0x8, 0x3, 0x3}]}, @ETHTOOL_A_STRSET_COUNTS_ONLY={0x4}, @ETHTOOL_A_STRSET_HEADER={0x34, 0x1, 0x0, 0x1, [@ETHTOOL_A_HEADER_DEV_NAME={0x14, 0x2, 'wg2\x00'}, @ETHTOOL_A_HEADER_FLAGS={0x8, 0x3, 0x2}, @ETHTOOL_A_HEADER_DEV_NAME={0x14, 0x2, 'ip6_vti0\x00'}]}]}, 0x1a0}, 0x1, 0x0, 0x0, 0x20000000}, 0x4040800)

16:47:58 executing program 1:
mkdir(&(0x7f0000000140)='./file0\x00', 0x0)
r0 = inotify_init1(0x0)
inotify_add_watch(r0, &(0x7f0000000b80)='./file0\x00', 0x86000cf2)
socket$inet_mptcp(0x2, 0x1, 0x106)
r1 = socket$inet_mptcp(0x2, 0x1, 0x106)
r2 = dup(r1)
sendmmsg$inet(r2, &(0x7f0000000300)=[{{&(0x7f0000000080)={0x2, 0x4001, @remote}, 0x10, 0x0}}], 0x1, 0x2004c04f)
r3 = dup(r2)
sendmmsg$inet(r3, &(0x7f0000000300)=[{{&(0x7f0000000080)={0x2, 0x4001, @remote}, 0x10, 0x0}}], 0x1, 0x2004c04f)
inotify_add_watch(r3, &(0x7f00000001c0)='./file0\x00', 0x0)
rmdir(&(0x7f00000000c0)='./file0\x00')
r4 = syz_open_procfs(0xffffffffffffffff, &(0x7f0000000040)='net/rt_cache\x00')
inotify_add_watch(r4, &(0x7f0000000080)='./file0\x00', 0x5000506)
read(r0, 0x0, 0x10000000)
inotify_add_watch(0xffffffffffffffff, &(0x7f0000000100)='./file0\x00', 0xe0000043)
r5 = dup(r4)
getsockopt$inet_sctp6_SCTP_I_WANT_MAPPED_V4_ADDR(r5, 0x84, 0xc, &(0x7f0000000000), &(0x7f0000000180)=0x4)
mkdir(&(0x7f0000000140)='./file0\x00', 0x0) (async)
inotify_init1(0x0) (async)
inotify_add_watch(r0, &(0x7f0000000b80)='./file0\x00', 0x86000cf2) (async)
socket$inet_mptcp(0x2, 0x1, 0x106) (async)
socket$inet_mptcp(0x2, 0x1, 0x106) (async)
dup(r1) (async)
sendmmsg$inet(r2, &(0x7f0000000300)=[{{&(0x7f0000000080)={0x2, 0x4001, @remote}, 0x10, 0x0}}], 0x1, 0x2004c04f) (async)
dup(r2) (async)
sendmmsg$inet(r3, &(0x7f0000000300)=[{{&(0x7f0000000080)={0x2, 0x4001, @remote}, 0x10, 0x0}}], 0x1, 0x2004c04f) (async)
inotify_add_watch(r3, &(0x7f00000001c0)='./file0\x00', 0x0) (async)
rmdir(&(0x7f00000000c0)='./file0\x00') (async)
syz_open_procfs(0xffffffffffffffff, &(0x7f0000000040)='net/rt_cache\x00') (async)
inotify_add_watch(r4, &(0x7f0000000080)='./file0\x00', 0x5000506) (async)
read(r0, 0x0, 0x10000000) (async)
inotify_add_watch(0xffffffffffffffff, &(0x7f0000000100)='./file0\x00', 0xe0000043) (async)
dup(r4) (async)
getsockopt$inet_sctp6_SCTP_I_WANT_MAPPED_V4_ADDR(r5, 0x84, 0xc, &(0x7f0000000000), &(0x7f0000000180)=0x4) (async)

16:47:58 executing program 5:
ioctl$TIOCSWINSZ(0xffffffffffffffff, 0x5414, &(0x7f0000000000)={0x0, 0xff3})
syz_clone(0x801000, &(0x7f0000000040), 0x0, &(0x7f0000000080), 0x0, 0x0) (async)
ioctl$TIOCSETD(0xffffffffffffffff, 0x5423, 0x0)
ioctl$TIOCSCTTY(0xffffffffffffffff, 0x540e, 0x0)
ioctl$KDMKTONE(0xffffffffffffffff, 0x4b30, 0x0)
r0 = syz_io_uring_complete(0x0)
r1 = socket$inet_mptcp(0x2, 0x1, 0x106)
r2 = dup(r1)
ioctl$KDMKTONE(r2, 0x4b30, 0x20) (async)
sendmmsg$inet(r2, &(0x7f0000000300)=[{{&(0x7f0000000080)={0x2, 0x4001, @remote}, 0x10, 0x0}}], 0x1, 0x2004c04f)
setsockopt$netlink_NETLINK_PKTINFO(r2, 0x10e, 0x3, &(0x7f0000000040)=0x7fffffff, 0x4)
ioctl$TIOCSCTTY(r0, 0x540e, 0x8) (async)
ioctl$PIO_UNIMAPCLR(0xffffffffffffffff, 0x4b68, 0x0) (async)
ioctl$sock_ipv4_tunnel_SIOCADDTUNNEL(0xffffffffffffffff, 0x89f1, 0x0)
```

**Comment by pabeni** [comment] 2023-06-05 13:50
@cpaasch: it looks this was observed again. Do you have the relevant logs (~60s before for the given process) available?

The system reports only leaks for the mptcp subflow contenxt, right? no leak for other object types?

That is quite strange confusing, as it means that either the msk has been freed before the context - should not happen due to reference acquired by the latter on the first - or the context has been removed by the msk conn_list but not freed - again strange because the context is freed at removal time.

**Comment by cpaasch** [comment] 2023-06-05 19:56
Yes, that's the only leak that is reported.

Here are the progs from 60s before (removed the ones that have no MPTCP:

```
06:38:15 executing program 5:
ioctl$sock_kcm_SIOCKCMCLONE(0xffffffffffffffff, 0x89e2, &(0x7f0000000080)={<r0=>0xffffffffffffffff})
ioctl$SIOCGSTAMP(r0, 0x8906, &(0x7f0000000100)) (async)
r1 = socket$inet6_mptcp(0xa, 0x1, 0x106)
bind$inet6(r1, &(0x7f0000000180)={0xa, 0x4e23, 0x0, @loopback}, 0x1c) (async)
listen(r1, 0x0) (async)
r2 = socket$inet6_mptcp(0xa, 0x1, 0x106)
setsockopt$sock_int(r1, 0x1, 0x8, &(0x7f0000000000), 0x4) (async)
connect$inet6(r2, &(0x7f00000000c0)={0xa, 0x4e23, 0x0, @loopback}, 0x63) (async)
sendto$inet6(r2, &(0x7f0000000040)="eb", 0x7fdc, 0x0, 0x0, 0x0) (async)
r3 = accept(r1, 0x0, 0x0)
syz_genetlink_get_family_id$nl80211(&(0x7f0000000140), r3)

[ 2647.904225] netlink: 'syz-executor.7': attribute type 1 has an invalid length.
[ 2647.907756] IPVS: set_ctl: invalid protocol: 0 10.1.1.1:20002
06:38:15 executing program 5:
ioctl$sock_kcm_SIOCKCMCLONE(0xffffffffffffffff, 0x89e2, &(0x7f0000000080)={<r0=>0xffffffffffffffff})
ioctl$SIOCGSTAMP(r0, 0x8906, &(0x7f0000000100))
r1 = socket$inet6_mptcp(0xa, 0x1, 0x106)
bind$inet6(r1, &(0x7f0000000180)={0xa, 0x4e23, 0x0, @loopback}, 0x1c)
listen(r1, 0x0) (async)
r2 = socket$inet6_mptcp(0xa, 0x1, 0x106)
setsockopt$sock_int(r1, 0x1, 0x8, &(0x7f0000000000), 0x4) (async)
connect$inet6(r2, &(0x7f00000000c0)={0xa, 0x4e23, 0x0, @loopback}, 0x63) (async)
sendto$inet6(r2, &(0x7f0000000040)="eb", 0x7fdc, 0x0, 0x0, 0x0)
r3 = accept(r1, 0x0, 0x0)
syz_genetlink_get_family_id$nl80211(&(0x7f0000000140), r3)
```

**Comment by cpaasch** [comment] 2023-06-05 20:09
FWIW, had a similar one in `subflow_ulp_clone`:

```
BUG: memory leak
unreferenced object 0xffff88812cf24700 (size 256):
  comm "softirq", pid 0, jiffies 4297315037 (age 62.705s)
  hex dump (first 32 bytes):
    00 01 00 00 00 00 ad de 22 01 00 00 00 00 ad de  ........".......
    89 39 6f 00 00 00 00 00 bc 62 aa 34 fe 02 f9 e3  .9o......b.4....
  backtrace:
    [<000000008ef4f370>] __kmem_cache_alloc_node+0xf6/0x1e0 mm/slub.c:3451
    [<00000000fc042d3f>] kmalloc_trace+0x2a/0xa0 mm/slab_common.c:1057
    [<00000000b58967d1>] subflow_ulp_clone+0x9b/0x2e0 include/linux/slab.h:559
    [<0000000071c354ef>] inet_csk_clone_lock+0x14e/0x170 net/ipv4/inet_connection_sock.c:1125
    [<000000006c92121a>] tcp_create_openreq_child+0x30/0x530 net/ipv4/tcp_minisocks.c:491
    [<0000000059dafe86>] tcp_v6_syn_recv_sock+0x26f/0xa70 net/ipv6/tcp_ipv6.c:1278
    [<0000000082dfc2c4>] subflow_syn_recv_sock+0x304/0x7e0 net/mptcp/subflow.c:794
    [<000000001861be1d>] tcp_get_cookie_sock+0x56/0x380 net/ipv4/syncookies.c:207
    [<00000000bf719ef9>] cookie_v6_check+0x892/0x920 net/ipv6/syncookies.c:260
    [<000000006c790a2f>] tcp_v6_do_rcv+0x629/0x870 net/ipv6/tcp_ipv6.c:1142
    [<00000000a41ad9b8>] tcp_v6_rcv+0x1005/0x12e0 net/ipv6/tcp_ipv6.c:1735
    [<000000009f29a2b4>] ip6_protocol_deliver_rcu+0x637/0xba0 net/ipv6/ip6_input.c:437
    [<0000000022d0ce24>] ip6_input+0x82/0x150 net/ipv6/ip6_input.c:482
    [<00000000afaf761e>] ipv6_rcv+0x5d/0x120 include/linux/netfilter.h:303
    [<0000000028ea0906>] __netif_receive_skb+0x84/0x210 net/core/dev.c:5491
    [<000000000885317c>] process_backlog+0x12e/0x200 net/core/dev.c:5933

BUG: leak checking failed
```

**Comment by pabeni** [comment] 2023-06-07 10:41
@cpaasch: could you please try to reproduce this issue including the following debug patch below? it should include additional info about the subflow status into the memleak report
[diffs.txt](https://github.com/multipath-tcp/mptcp_net-next/files/11676033/diffs.txt)

**Comment by cpaasch** [comment] 2023-06-08 15:57
@pabeni : Here we are:

```
sendmsg$nl_route_sched(r0, &(0x7f0000000140)={0x0, 0x0, &(0x7f0000000100)={&(0x7f00000003c0)=@newqdisc={0x38, 0x24, 0x521, 0x600, 0x0, {0x0, 0x0, 0x0, r2, {}, {0xffff, 0xffff}}, [@qdisc_kind_options=@q_tbf={{0x8}, {0x4}}, @TCA_EGRESS_BLOCK={0x8}]}, 0x38}}, 0x0)
BUG: memory leak
unreferenced object 0xffff8881329fee00 (size 512):
  comm "syz-executor.5", pid 17476, jiffies 4296656985 (age 66.637s)
  hex dump (first 288 bytes):
    00 01 00 00 00 00 ad de 22 01 00 00 00 00 ad de  ........".......
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 01 00 08 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 a8 ee 9f 32 81 88 ff ff  ...........2....
    a8 ee 9f 32 81 88 ff ff 00 00 00 00 00 00 00 00  ...2............
    c0 ce 39 04 81 88 ff ff 80 8f 09 2e 81 88 ff ff  ..9.............
    20 86 cd 82 ff ff ff ff 40 03 d1 81 ff ff ff ff   .......@.......
    c0 03 d1 81 ff ff ff ff 00 00 00 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 00 c0 1a 00 01 00 00 00  ................
    00 c0 1a 00 01 00 00 00 07 00 00 00 07 00 00 00  ................
    01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
  backtrace:
    [<0000000031dc693e>] __kmem_cache_alloc_node+0xf6/0x1e0 mm/slub.c:3451
    [<0000000091bdfbc8>] kmalloc_trace+0x2a/0xa0 mm/slab_common.c:1057
    [<0000000037a6639d>] kmalloc include/linux/slab.h:559 [inline]
    [<0000000037a6639d>] kzalloc include/linux/slab.h:680 [inline]
    [<0000000037a6639d>] subflow_create_ctx net/mptcp/subflow.c:1725 [inline]
    [<0000000037a6639d>] subflow_ulp_init+0x4e/0x170 net/mptcp/subflow.c:1876
    [<000000003bec1929>] tcp_set_ulp+0x181/0x1c0 net/ipv4/tcp_ulp.c:146
    [<00000000fbdbbb1e>] mptcp_subflow_create_socket+0x228/0x440 net/mptcp/subflow.c:1688
    [<000000009d00fba3>] __mptcp_nmpc_socket+0x9b/0x210 net/mptcp/protocol.c:89
    [<000000001a085920>] mptcp_sendmsg_fastopen+0x4c/0x200 net/mptcp/protocol.c:1734
    [<00000000990d3950>] mptcp_sendmsg+0x766/0x830 net/mptcp/protocol.c:1791
    [<000000006ed7725f>] ____sys_sendmsg+0x389/0x3d0 net/socket.c:724
    [<00000000bfd282b9>] ___sys_sendmsg+0x143/0x190 net/socket.c:2559
    [<0000000076c3b545>] __sys_sendmmsg+0x185/0x340 net/socket.c:2645
    [<00000000e3ee18f3>] __do_sys_sendmmsg net/socket.c:2674 [inline]
    [<00000000e3ee18f3>] __se_sys_sendmmsg net/socket.c:2671 [inline]
    [<00000000e3ee18f3>] __x64_sys_sendmmsg+0x25/0x30 net/socket.c:2671
    [<000000000b426adb>] do_syscall_x64 arch/x86/entry/common.c:50 [inline]
    [<000000000b426adb>] do_syscall_64+0x45/0xa0 arch/x86/entry/common.c:80
    [<00000000d72afcc8>] entry_SYSCALL_64_after_hwframe+0x72/0xdc

BUG: leak checking failed
```

**Comment by pabeni** [comment] 2023-06-08 16:30
@cpaasch: thanks that contains good info, even if it's quite confusing. The value for added debug fields are:

ulp_release_stamp == 4296720384 // 63399 jiffies later the allocation, ~3 sec before the splat
list_del_stamp            4296720384 // 
list_del_state              TCP_CLOSE
list_del_msk_state     TCP_CLOSE
ulp_release_free        true

which in turn means that the subflow context went through both __mptcp_close_ssk (list_del_stamp is not 0) subflow_ulp_release (and ulp_release_stamp is not 0), roughly at the same time (the 2 stamps have the same value). both the msk and the ssk were closed when  __mptcp_close_ssk executed. 

The confusing part is that ulp_release_free is true, meaning subflow_ulp_release() invoked kfree_rcu() on the relevant context, which in turn should either cause an RCU dbg splat on some esoteric bug or free the context. Do you have the log still available ? perhaps there are some relevant messages ~3.238 seconds before the splat...

**Comment by pabeni** [comment] 2023-06-08 17:26
(this is mostly a dup of IRC conversation)
Basically the previous commit "proofs" that the mptcp code invokes kfree_rcu() on the leaked context.
The specified KCONFIG uses TREE_RCU. It looks like tree rcu can delay a free up to KFREE_DRAIN_JIFFIES (or more ?!?) == 5s. If kmemleak does not cope correctly with the RCU internal data structure (big if!) the above report could be caused by a false positive/"transient leak".
@cpaasch: if you observe the leak again, could you please wait at least 5 seconds and perform another kmemleak scan manually?

echo scan > /sys/kernel/debug/kmemleak
cat /sys/kernel/debug/kmemleak

if the leak is "transient" should not be reported again.

**Comment by pabeni** [comment] 2023-06-09 06:50
As per IRC discussion, I believe the issue should be a kmemleak artifact that could be hidden setting MSECS_MIN_AGE to 70 seconds. @cpaasch: could you apply that change in your testbed?

**Comment by matttbe** [comment] 2023-06-09 07:12
Impressive debug session, thank you for having shared this!

What should we do if Christoph is not able to reproduce the issue with `MSECS_MIN_AGE` set to 70? Would it make sense to send a patch upstream? Or only applying that in our tree (in `DO-NOT-MERGE: mptcp: improve code coverage for CI` commit for example)?

**Comment by cpaasch** [comment] 2023-06-09 14:21
70 seconds is the right value specifically for this particular syzkaller panic. Other scenarios/traffic flows/… may have different times.

If we believe it is a kmemleak bug with rcu free, we probably should report it.

**Comment by pabeni** [comment] 2023-06-09 14:45
> 70 seconds is the right value specifically for this particular syzkaller panic. Other scenarios/traffic flows/… may have different times.
> 
> If we believe it is a kmemleak bug with rcu free, we probably should report it.

Indeed we should report to kmemleak maintainers, if we prove this issue is really a kmemleak artifact. But first we need to see the issue disappear with the MSECS_MIN_AGE change ;)

In the meantime we could keep the not-upstreamable patch in our tree to allow syzkaller doing it's work.

**Comment by cpaasch** [comment] 2023-06-09 16:04
Here is a reproducer (not MPTCP-related), that triggers a leak-report in `copy_net_ns()`. Increasing the MSECS_MIN_AGE to 10s "fixes it":

```
# {Threaded:false Repeat:true RepeatTimes:0 Procs:8 Slowdown:1 Sandbox: SandboxArg:0 Leak:true NetInjection:false NetDevices:false NetReset:false Cgroups:false BinfmtMisc:false CloseFDs:false KCSAN:false DevlinkPCI:false NicVF:false USB:false VhciInjection:false Wifi:false IEEE802154:false Sysctl:false UseTmpDir:false HandleSegv:false Repro:false Trace:false LegacyOptions:{Collide:false Fault:false FaultCall:0 FaultNth:0}}
rt_sigaction(0x7, 0x0, 0x0, 0x0, 0x0)
syz_clone(0xe406c100, 0x0, 0x0, 0x0, 0x0, 0x0)
gettid()
```

The "leak" is on `net->key_domain`, because it ends up doing `kfree_rcu` in `key_put_tag`.

**Comment by cpaasch** [comment] 2023-06-13 16:44
FYI - no leaks yet since I move to 70sec Min_Age.

**Comment by cpaasch** [comment] 2023-06-28 16:35
@pabeni - what shall we do about this? Reach out to kmemleak-team ?

**Comment by matttbe** [comment] 2023-09-12 12:56
Catalin has shared a second patch fixing this issue: https://lore.kernel.org/mptcp/ZPizxVT5s9JA5MPw@arm.com/

I'm going to applying it in our tree and close this ticket.

**Closed as completed** 2023-09-12 13:33 UTC
Labels: bug, syzkaller
